// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_FFT (
std::complex<ap_fixed<16, 8, (ap_q_mode) 5, (ap_o_mode)3, 0> > data_IN[32],
std::complex<ap_fixed<16, 8, (ap_q_mode) 5, (ap_o_mode)3, 0> > data_OUT[32]);
