// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _FFT0_HH_
#define _FFT0_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "FFT_mul_mul_16s_1bkb.h"
#include "FFT_mac_mulsub_16cud.h"
#include "FFT_mac_muladd_9sdEe.h"
#include "FFT0_W_M_real_V.h"
#include "FFT0_W_M_imag_V.h"

namespace ap_rtl {

struct FFT0 : public sc_module {
    // Port declarations 24
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<6> > FFT_stage;
    sc_in< sc_lv<6> > pass_check;
    sc_in< sc_lv<4> > index_shift;
    sc_in< sc_lv<4> > pass_shift;
    sc_out< sc_lv<5> > data_IN_M_real_V_address0;
    sc_out< sc_logic > data_IN_M_real_V_ce0;
    sc_in< sc_lv<16> > data_IN_M_real_V_q0;
    sc_out< sc_lv<5> > data_IN_M_imag_V_address0;
    sc_out< sc_logic > data_IN_M_imag_V_ce0;
    sc_in< sc_lv<16> > data_IN_M_imag_V_q0;
    sc_out< sc_lv<5> > data_OUT_M_real_V_address0;
    sc_out< sc_logic > data_OUT_M_real_V_ce0;
    sc_out< sc_logic > data_OUT_M_real_V_we0;
    sc_out< sc_lv<16> > data_OUT_M_real_V_d0;
    sc_out< sc_lv<5> > data_OUT_M_imag_V_address0;
    sc_out< sc_logic > data_OUT_M_imag_V_ce0;
    sc_out< sc_logic > data_OUT_M_imag_V_we0;
    sc_out< sc_lv<16> > data_OUT_M_imag_V_d0;


    // Module declarations
    FFT0(sc_module_name name);
    SC_HAS_PROCESS(FFT0);

    ~FFT0();

    sc_trace_file* mVcdFile;

    FFT0_W_M_real_V* W_M_real_V_U;
    FFT0_W_M_imag_V* W_M_imag_V_U;
    FFT_mul_mul_16s_1bkb<1,1,16,10,24>* FFT_mul_mul_16s_1bkb_U1;
    FFT_mul_mul_16s_1bkb<1,1,16,10,24>* FFT_mul_mul_16s_1bkb_U2;
    FFT_mac_mulsub_16cud<1,1,16,9,24,24>* FFT_mac_mulsub_16cud_U3;
    FFT_mac_muladd_9sdEe<1,1,9,16,24,24>* FFT_mac_muladd_9sdEe_U4;
    sc_signal< sc_lv<6> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<4> > W_M_real_V_address0;
    sc_signal< sc_logic > W_M_real_V_ce0;
    sc_signal< sc_lv<10> > W_M_real_V_q0;
    sc_signal< sc_lv<4> > W_M_imag_V_address0;
    sc_signal< sc_logic > W_M_imag_V_ce0;
    sc_signal< sc_lv<9> > W_M_imag_V_q0;
    sc_signal< sc_lv<32> > pass_shift_cast_fu_219_p1;
    sc_signal< sc_lv<32> > pass_shift_cast_reg_438;
    sc_signal< sc_lv<32> > index_shift_cast_fu_223_p1;
    sc_signal< sc_lv<32> > index_shift_cast_reg_443;
    sc_signal< sc_lv<32> > FFT_stage_cast1_fu_227_p1;
    sc_signal< sc_lv<32> > FFT_stage_cast1_reg_448;
    sc_signal< sc_lv<32> > tmp_cast_fu_241_p1;
    sc_signal< sc_lv<32> > tmp_cast_reg_453;
    sc_signal< sc_lv<32> > tmp_cast_11_fu_255_p1;
    sc_signal< sc_lv<32> > tmp_cast_11_reg_458;
    sc_signal< sc_lv<5> > i_1_fu_265_p2;
    sc_signal< sc_lv<5> > i_1_reg_466;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<32> > Ulimit_fu_281_p2;
    sc_signal< sc_lv<32> > Ulimit_reg_471;
    sc_signal< sc_lv<1> > exitcond_fu_259_p2;
    sc_signal< sc_lv<32> > butterfly_span_2_fu_323_p3;
    sc_signal< sc_lv<32> > butterfly_span_2_reg_487;
    sc_signal< sc_lv<32> > butterfly_pass_2_fu_331_p3;
    sc_signal< sc_lv<32> > butterfly_pass_2_reg_492;
    sc_signal< sc_lv<64> > tmp_4_fu_343_p1;
    sc_signal< sc_lv<64> > tmp_4_reg_497;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<10> > p_r_M_real_V_reg_513;
    sc_signal< sc_lv<9> > p_r_M_imag_V_reg_518;
    sc_signal< sc_lv<24> > tmp_1_fu_349_p1;
    sc_signal< sc_lv<24> > tmp_1_reg_523;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<24> > tmp_9_fu_356_p1;
    sc_signal< sc_lv<24> > tmp_9_reg_528;
    sc_signal< sc_lv<24> > tmp1_i_i_cast_fu_412_p2;
    sc_signal< sc_lv<24> > tmp1_i_i_cast_reg_533;
    sc_signal< sc_lv<24> > tmp_i_i_cast_fu_418_p2;
    sc_signal< sc_lv<24> > tmp_i_i_cast_reg_538;
    sc_signal< sc_lv<64> > tmp_5_fu_360_p1;
    sc_signal< sc_lv<64> > tmp_5_reg_543;
    sc_signal< sc_lv<16> > complex_M_real_V_wr_1_fu_400_p2;
    sc_signal< sc_lv<16> > complex_M_real_V_wr_1_reg_559;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<16> > complex_M_imag_V_wr_1_fu_406_p2;
    sc_signal< sc_lv<16> > complex_M_imag_V_wr_1_reg_564;
    sc_signal< sc_lv<32> > butterfly_span_reg_186;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<32> > butterfly_pass_reg_197;
    sc_signal< sc_lv<5> > i_reg_208;
    sc_signal< sc_lv<64> > tmp_3_fu_287_p1;
    sc_signal< sc_lv<16> > complex_M_real_V_wr_fu_386_p2;
    sc_signal< sc_lv<16> > complex_M_imag_V_wr_fu_393_p2;
    sc_signal< sc_lv<5> > tmp_11_fu_231_p1;
    sc_signal< sc_lv<5> > tmp_fu_235_p2;
    sc_signal< sc_lv<5> > tmp_12_fu_245_p1;
    sc_signal< sc_lv<5> > tmp_s_fu_249_p2;
    sc_signal< sc_lv<32> > tmp_2_fu_276_p2;
    sc_signal< sc_lv<32> > index_fu_271_p2;
    sc_signal< sc_lv<1> > tmp_7_fu_304_p2;
    sc_signal< sc_lv<32> > butterfly_pass_3_fu_309_p2;
    sc_signal< sc_lv<1> > tmp_6_fu_293_p2;
    sc_signal< sc_lv<32> > butterfly_span_1_fu_298_p2;
    sc_signal< sc_lv<32> > butterfly_pass_1_fu_315_p3;
    sc_signal< sc_lv<32> > Llimit_fu_339_p2;
    sc_signal< sc_lv<24> > grp_fu_424_p3;
    sc_signal< sc_lv<24> > grp_fu_431_p3;
    sc_signal< sc_lv<16> > p_Val2_3_fu_368_p4;
    sc_signal< sc_lv<16> > p_Val2_5_fu_377_p4;
    sc_signal< sc_lv<10> > tmp1_i_i_cast_fu_412_p1;
    sc_signal< sc_lv<24> > tmp_8_fu_353_p1;
    sc_signal< sc_lv<10> > tmp_i_i_cast_fu_418_p1;
    sc_signal< sc_lv<16> > grp_fu_424_p0;
    sc_signal< sc_lv<9> > grp_fu_424_p1;
    sc_signal< sc_lv<24> > tmp_10_fu_365_p1;
    sc_signal< sc_lv<9> > grp_fu_431_p0;
    sc_signal< sc_lv<16> > grp_fu_431_p1;
    sc_signal< sc_lv<6> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<6> ap_ST_fsm_state1;
    static const sc_lv<6> ap_ST_fsm_state2;
    static const sc_lv<6> ap_ST_fsm_state3;
    static const sc_lv<6> ap_ST_fsm_state4;
    static const sc_lv<6> ap_ST_fsm_state5;
    static const sc_lv<6> ap_ST_fsm_state6;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<5> ap_const_lv5_1F;
    static const sc_lv<5> ap_const_lv5_10;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<1> ap_const_lv1_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_FFT_stage_cast1_fu_227_p1();
    void thread_Llimit_fu_339_p2();
    void thread_Ulimit_fu_281_p2();
    void thread_W_M_imag_V_address0();
    void thread_W_M_imag_V_ce0();
    void thread_W_M_real_V_address0();
    void thread_W_M_real_V_ce0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_butterfly_pass_1_fu_315_p3();
    void thread_butterfly_pass_2_fu_331_p3();
    void thread_butterfly_pass_3_fu_309_p2();
    void thread_butterfly_span_1_fu_298_p2();
    void thread_butterfly_span_2_fu_323_p3();
    void thread_complex_M_imag_V_wr_1_fu_406_p2();
    void thread_complex_M_imag_V_wr_fu_393_p2();
    void thread_complex_M_real_V_wr_1_fu_400_p2();
    void thread_complex_M_real_V_wr_fu_386_p2();
    void thread_data_IN_M_imag_V_address0();
    void thread_data_IN_M_imag_V_ce0();
    void thread_data_IN_M_real_V_address0();
    void thread_data_IN_M_real_V_ce0();
    void thread_data_OUT_M_imag_V_address0();
    void thread_data_OUT_M_imag_V_ce0();
    void thread_data_OUT_M_imag_V_d0();
    void thread_data_OUT_M_imag_V_we0();
    void thread_data_OUT_M_real_V_address0();
    void thread_data_OUT_M_real_V_ce0();
    void thread_data_OUT_M_real_V_d0();
    void thread_data_OUT_M_real_V_we0();
    void thread_exitcond_fu_259_p2();
    void thread_grp_fu_424_p0();
    void thread_grp_fu_424_p1();
    void thread_grp_fu_431_p0();
    void thread_grp_fu_431_p1();
    void thread_i_1_fu_265_p2();
    void thread_index_fu_271_p2();
    void thread_index_shift_cast_fu_223_p1();
    void thread_p_Val2_3_fu_368_p4();
    void thread_p_Val2_5_fu_377_p4();
    void thread_pass_shift_cast_fu_219_p1();
    void thread_tmp1_i_i_cast_fu_412_p1();
    void thread_tmp_10_fu_365_p1();
    void thread_tmp_11_fu_231_p1();
    void thread_tmp_12_fu_245_p1();
    void thread_tmp_1_fu_349_p1();
    void thread_tmp_2_fu_276_p2();
    void thread_tmp_3_fu_287_p1();
    void thread_tmp_4_fu_343_p1();
    void thread_tmp_5_fu_360_p1();
    void thread_tmp_6_fu_293_p2();
    void thread_tmp_7_fu_304_p2();
    void thread_tmp_8_fu_353_p1();
    void thread_tmp_9_fu_356_p1();
    void thread_tmp_cast_11_fu_255_p1();
    void thread_tmp_cast_fu_241_p1();
    void thread_tmp_fu_235_p2();
    void thread_tmp_i_i_cast_fu_418_p1();
    void thread_tmp_s_fu_249_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
