// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "FFT0.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic FFT0::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic FFT0::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> FFT0::ap_ST_fsm_state1 = "1";
const sc_lv<6> FFT0::ap_ST_fsm_state2 = "10";
const sc_lv<6> FFT0::ap_ST_fsm_state3 = "100";
const sc_lv<6> FFT0::ap_ST_fsm_state4 = "1000";
const sc_lv<6> FFT0::ap_ST_fsm_state5 = "10000";
const sc_lv<6> FFT0::ap_ST_fsm_state6 = "100000";
const sc_lv<32> FFT0::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> FFT0::ap_const_lv32_1 = "1";
const sc_lv<1> FFT0::ap_const_lv1_0 = "0";
const sc_lv<32> FFT0::ap_const_lv32_2 = "10";
const sc_lv<32> FFT0::ap_const_lv32_3 = "11";
const sc_lv<32> FFT0::ap_const_lv32_4 = "100";
const sc_lv<32> FFT0::ap_const_lv32_5 = "101";
const sc_lv<5> FFT0::ap_const_lv5_0 = "00000";
const sc_lv<5> FFT0::ap_const_lv5_1F = "11111";
const sc_lv<5> FFT0::ap_const_lv5_10 = "10000";
const sc_lv<5> FFT0::ap_const_lv5_1 = "1";
const sc_lv<32> FFT0::ap_const_lv32_8 = "1000";
const sc_lv<32> FFT0::ap_const_lv32_17 = "10111";
const sc_lv<1> FFT0::ap_const_lv1_1 = "1";
const bool FFT0::ap_const_boolean_1 = true;

FFT0::FFT0(sc_module_name name) : sc_module(name), mVcdFile(0) {
    W_M_real_V_U = new FFT0_W_M_real_V("W_M_real_V_U");
    W_M_real_V_U->clk(ap_clk);
    W_M_real_V_U->reset(ap_rst);
    W_M_real_V_U->address0(W_M_real_V_address0);
    W_M_real_V_U->ce0(W_M_real_V_ce0);
    W_M_real_V_U->q0(W_M_real_V_q0);
    W_M_imag_V_U = new FFT0_W_M_imag_V("W_M_imag_V_U");
    W_M_imag_V_U->clk(ap_clk);
    W_M_imag_V_U->reset(ap_rst);
    W_M_imag_V_U->address0(W_M_imag_V_address0);
    W_M_imag_V_U->ce0(W_M_imag_V_ce0);
    W_M_imag_V_U->q0(W_M_imag_V_q0);
    FFT_mul_mul_16s_1bkb_U1 = new FFT_mul_mul_16s_1bkb<1,1,16,10,24>("FFT_mul_mul_16s_1bkb_U1");
    FFT_mul_mul_16s_1bkb_U1->din0(data_IN_M_real_V_q0);
    FFT_mul_mul_16s_1bkb_U1->din1(tmp1_i_i_cast_fu_412_p1);
    FFT_mul_mul_16s_1bkb_U1->dout(tmp1_i_i_cast_fu_412_p2);
    FFT_mul_mul_16s_1bkb_U2 = new FFT_mul_mul_16s_1bkb<1,1,16,10,24>("FFT_mul_mul_16s_1bkb_U2");
    FFT_mul_mul_16s_1bkb_U2->din0(data_IN_M_imag_V_q0);
    FFT_mul_mul_16s_1bkb_U2->din1(tmp_i_i_cast_fu_418_p1);
    FFT_mul_mul_16s_1bkb_U2->dout(tmp_i_i_cast_fu_418_p2);
    FFT_mac_mulsub_16cud_U3 = new FFT_mac_mulsub_16cud<1,1,16,9,24,24>("FFT_mac_mulsub_16cud_U3");
    FFT_mac_mulsub_16cud_U3->din0(grp_fu_424_p0);
    FFT_mac_mulsub_16cud_U3->din1(grp_fu_424_p1);
    FFT_mac_mulsub_16cud_U3->din2(tmp1_i_i_cast_reg_533);
    FFT_mac_mulsub_16cud_U3->dout(grp_fu_424_p3);
    FFT_mac_muladd_9sdEe_U4 = new FFT_mac_muladd_9sdEe<1,1,9,16,24,24>("FFT_mac_muladd_9sdEe_U4");
    FFT_mac_muladd_9sdEe_U4->din0(grp_fu_431_p0);
    FFT_mac_muladd_9sdEe_U4->din1(grp_fu_431_p1);
    FFT_mac_muladd_9sdEe_U4->din2(tmp_i_i_cast_reg_538);
    FFT_mac_muladd_9sdEe_U4->dout(grp_fu_431_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_FFT_stage_cast1_fu_227_p1);
    sensitive << ( FFT_stage );

    SC_METHOD(thread_Llimit_fu_339_p2);
    sensitive << ( FFT_stage_cast1_reg_448 );
    sensitive << ( Ulimit_reg_471 );

    SC_METHOD(thread_Ulimit_fu_281_p2);
    sensitive << ( butterfly_span_reg_186 );
    sensitive << ( tmp_2_fu_276_p2 );

    SC_METHOD(thread_W_M_imag_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_3_fu_287_p1 );

    SC_METHOD(thread_W_M_imag_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_W_M_real_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_3_fu_287_p1 );

    SC_METHOD(thread_W_M_real_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_259_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_259_p2 );

    SC_METHOD(thread_butterfly_pass_1_fu_315_p3);
    sensitive << ( tmp_7_fu_304_p2 );
    sensitive << ( butterfly_pass_3_fu_309_p2 );

    SC_METHOD(thread_butterfly_pass_2_fu_331_p3);
    sensitive << ( butterfly_pass_reg_197 );
    sensitive << ( tmp_6_fu_293_p2 );
    sensitive << ( butterfly_pass_1_fu_315_p3 );

    SC_METHOD(thread_butterfly_pass_3_fu_309_p2);
    sensitive << ( butterfly_pass_reg_197 );

    SC_METHOD(thread_butterfly_span_1_fu_298_p2);
    sensitive << ( butterfly_span_reg_186 );

    SC_METHOD(thread_butterfly_span_2_fu_323_p3);
    sensitive << ( tmp_6_fu_293_p2 );
    sensitive << ( butterfly_span_1_fu_298_p2 );

    SC_METHOD(thread_complex_M_imag_V_wr_1_fu_406_p2);
    sensitive << ( data_IN_M_imag_V_q0 );
    sensitive << ( p_Val2_5_fu_377_p4 );

    SC_METHOD(thread_complex_M_imag_V_wr_fu_393_p2);
    sensitive << ( data_IN_M_imag_V_q0 );
    sensitive << ( p_Val2_5_fu_377_p4 );

    SC_METHOD(thread_complex_M_real_V_wr_1_fu_400_p2);
    sensitive << ( data_IN_M_real_V_q0 );
    sensitive << ( p_Val2_3_fu_368_p4 );

    SC_METHOD(thread_complex_M_real_V_wr_fu_386_p2);
    sensitive << ( data_IN_M_real_V_q0 );
    sensitive << ( p_Val2_3_fu_368_p4 );

    SC_METHOD(thread_data_IN_M_imag_V_address0);
    sensitive << ( tmp_4_fu_343_p1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_5_fu_360_p1 );

    SC_METHOD(thread_data_IN_M_imag_V_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_data_IN_M_real_V_address0);
    sensitive << ( tmp_4_fu_343_p1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_5_fu_360_p1 );

    SC_METHOD(thread_data_IN_M_real_V_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_data_OUT_M_imag_V_address0);
    sensitive << ( tmp_4_reg_497 );
    sensitive << ( tmp_5_reg_543 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_data_OUT_M_imag_V_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_data_OUT_M_imag_V_d0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( complex_M_imag_V_wr_1_reg_564 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( complex_M_imag_V_wr_fu_393_p2 );

    SC_METHOD(thread_data_OUT_M_imag_V_we0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_data_OUT_M_real_V_address0);
    sensitive << ( tmp_4_reg_497 );
    sensitive << ( tmp_5_reg_543 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_data_OUT_M_real_V_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_data_OUT_M_real_V_d0);
    sensitive << ( complex_M_real_V_wr_1_reg_559 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( complex_M_real_V_wr_fu_386_p2 );

    SC_METHOD(thread_data_OUT_M_real_V_we0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_exitcond_fu_259_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_reg_208 );

    SC_METHOD(thread_grp_fu_424_p0);
    sensitive << ( tmp_9_reg_528 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_grp_fu_424_p1);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_10_fu_365_p1 );

    SC_METHOD(thread_grp_fu_431_p0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_10_fu_365_p1 );

    SC_METHOD(thread_grp_fu_431_p1);
    sensitive << ( tmp_1_reg_523 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_i_1_fu_265_p2);
    sensitive << ( i_reg_208 );

    SC_METHOD(thread_index_fu_271_p2);
    sensitive << ( index_shift_cast_reg_443 );
    sensitive << ( butterfly_span_reg_186 );

    SC_METHOD(thread_index_shift_cast_fu_223_p1);
    sensitive << ( index_shift );

    SC_METHOD(thread_p_Val2_3_fu_368_p4);
    sensitive << ( grp_fu_424_p3 );

    SC_METHOD(thread_p_Val2_5_fu_377_p4);
    sensitive << ( grp_fu_431_p3 );

    SC_METHOD(thread_pass_shift_cast_fu_219_p1);
    sensitive << ( pass_shift );

    SC_METHOD(thread_tmp1_i_i_cast_fu_412_p1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_8_fu_353_p1 );

    SC_METHOD(thread_tmp_10_fu_365_p1);
    sensitive << ( p_r_M_imag_V_reg_518 );

    SC_METHOD(thread_tmp_11_fu_231_p1);
    sensitive << ( FFT_stage );

    SC_METHOD(thread_tmp_12_fu_245_p1);
    sensitive << ( pass_check );

    SC_METHOD(thread_tmp_1_fu_349_p1);
    sensitive << ( data_IN_M_real_V_q0 );

    SC_METHOD(thread_tmp_2_fu_276_p2);
    sensitive << ( pass_shift_cast_reg_438 );
    sensitive << ( butterfly_pass_reg_197 );

    SC_METHOD(thread_tmp_3_fu_287_p1);
    sensitive << ( index_fu_271_p2 );

    SC_METHOD(thread_tmp_4_fu_343_p1);
    sensitive << ( Llimit_fu_339_p2 );

    SC_METHOD(thread_tmp_5_fu_360_p1);
    sensitive << ( Ulimit_reg_471 );

    SC_METHOD(thread_tmp_6_fu_293_p2);
    sensitive << ( tmp_cast_reg_453 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_259_p2 );
    sensitive << ( butterfly_span_reg_186 );

    SC_METHOD(thread_tmp_7_fu_304_p2);
    sensitive << ( tmp_cast_11_reg_458 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_259_p2 );
    sensitive << ( butterfly_pass_reg_197 );

    SC_METHOD(thread_tmp_8_fu_353_p1);
    sensitive << ( p_r_M_real_V_reg_513 );

    SC_METHOD(thread_tmp_9_fu_356_p1);
    sensitive << ( data_IN_M_imag_V_q0 );

    SC_METHOD(thread_tmp_cast_11_fu_255_p1);
    sensitive << ( tmp_s_fu_249_p2 );

    SC_METHOD(thread_tmp_cast_fu_241_p1);
    sensitive << ( tmp_fu_235_p2 );

    SC_METHOD(thread_tmp_fu_235_p2);
    sensitive << ( tmp_11_fu_231_p1 );

    SC_METHOD(thread_tmp_i_i_cast_fu_418_p1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_8_fu_353_p1 );

    SC_METHOD(thread_tmp_s_fu_249_p2);
    sensitive << ( tmp_12_fu_245_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_259_p2 );

    ap_CS_fsm = "000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "FFT0_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, FFT_stage, "(port)FFT_stage");
    sc_trace(mVcdFile, pass_check, "(port)pass_check");
    sc_trace(mVcdFile, index_shift, "(port)index_shift");
    sc_trace(mVcdFile, pass_shift, "(port)pass_shift");
    sc_trace(mVcdFile, data_IN_M_real_V_address0, "(port)data_IN_M_real_V_address0");
    sc_trace(mVcdFile, data_IN_M_real_V_ce0, "(port)data_IN_M_real_V_ce0");
    sc_trace(mVcdFile, data_IN_M_real_V_q0, "(port)data_IN_M_real_V_q0");
    sc_trace(mVcdFile, data_IN_M_imag_V_address0, "(port)data_IN_M_imag_V_address0");
    sc_trace(mVcdFile, data_IN_M_imag_V_ce0, "(port)data_IN_M_imag_V_ce0");
    sc_trace(mVcdFile, data_IN_M_imag_V_q0, "(port)data_IN_M_imag_V_q0");
    sc_trace(mVcdFile, data_OUT_M_real_V_address0, "(port)data_OUT_M_real_V_address0");
    sc_trace(mVcdFile, data_OUT_M_real_V_ce0, "(port)data_OUT_M_real_V_ce0");
    sc_trace(mVcdFile, data_OUT_M_real_V_we0, "(port)data_OUT_M_real_V_we0");
    sc_trace(mVcdFile, data_OUT_M_real_V_d0, "(port)data_OUT_M_real_V_d0");
    sc_trace(mVcdFile, data_OUT_M_imag_V_address0, "(port)data_OUT_M_imag_V_address0");
    sc_trace(mVcdFile, data_OUT_M_imag_V_ce0, "(port)data_OUT_M_imag_V_ce0");
    sc_trace(mVcdFile, data_OUT_M_imag_V_we0, "(port)data_OUT_M_imag_V_we0");
    sc_trace(mVcdFile, data_OUT_M_imag_V_d0, "(port)data_OUT_M_imag_V_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, W_M_real_V_address0, "W_M_real_V_address0");
    sc_trace(mVcdFile, W_M_real_V_ce0, "W_M_real_V_ce0");
    sc_trace(mVcdFile, W_M_real_V_q0, "W_M_real_V_q0");
    sc_trace(mVcdFile, W_M_imag_V_address0, "W_M_imag_V_address0");
    sc_trace(mVcdFile, W_M_imag_V_ce0, "W_M_imag_V_ce0");
    sc_trace(mVcdFile, W_M_imag_V_q0, "W_M_imag_V_q0");
    sc_trace(mVcdFile, pass_shift_cast_fu_219_p1, "pass_shift_cast_fu_219_p1");
    sc_trace(mVcdFile, pass_shift_cast_reg_438, "pass_shift_cast_reg_438");
    sc_trace(mVcdFile, index_shift_cast_fu_223_p1, "index_shift_cast_fu_223_p1");
    sc_trace(mVcdFile, index_shift_cast_reg_443, "index_shift_cast_reg_443");
    sc_trace(mVcdFile, FFT_stage_cast1_fu_227_p1, "FFT_stage_cast1_fu_227_p1");
    sc_trace(mVcdFile, FFT_stage_cast1_reg_448, "FFT_stage_cast1_reg_448");
    sc_trace(mVcdFile, tmp_cast_fu_241_p1, "tmp_cast_fu_241_p1");
    sc_trace(mVcdFile, tmp_cast_reg_453, "tmp_cast_reg_453");
    sc_trace(mVcdFile, tmp_cast_11_fu_255_p1, "tmp_cast_11_fu_255_p1");
    sc_trace(mVcdFile, tmp_cast_11_reg_458, "tmp_cast_11_reg_458");
    sc_trace(mVcdFile, i_1_fu_265_p2, "i_1_fu_265_p2");
    sc_trace(mVcdFile, i_1_reg_466, "i_1_reg_466");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, Ulimit_fu_281_p2, "Ulimit_fu_281_p2");
    sc_trace(mVcdFile, Ulimit_reg_471, "Ulimit_reg_471");
    sc_trace(mVcdFile, exitcond_fu_259_p2, "exitcond_fu_259_p2");
    sc_trace(mVcdFile, butterfly_span_2_fu_323_p3, "butterfly_span_2_fu_323_p3");
    sc_trace(mVcdFile, butterfly_span_2_reg_487, "butterfly_span_2_reg_487");
    sc_trace(mVcdFile, butterfly_pass_2_fu_331_p3, "butterfly_pass_2_fu_331_p3");
    sc_trace(mVcdFile, butterfly_pass_2_reg_492, "butterfly_pass_2_reg_492");
    sc_trace(mVcdFile, tmp_4_fu_343_p1, "tmp_4_fu_343_p1");
    sc_trace(mVcdFile, tmp_4_reg_497, "tmp_4_reg_497");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, p_r_M_real_V_reg_513, "p_r_M_real_V_reg_513");
    sc_trace(mVcdFile, p_r_M_imag_V_reg_518, "p_r_M_imag_V_reg_518");
    sc_trace(mVcdFile, tmp_1_fu_349_p1, "tmp_1_fu_349_p1");
    sc_trace(mVcdFile, tmp_1_reg_523, "tmp_1_reg_523");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, tmp_9_fu_356_p1, "tmp_9_fu_356_p1");
    sc_trace(mVcdFile, tmp_9_reg_528, "tmp_9_reg_528");
    sc_trace(mVcdFile, tmp1_i_i_cast_fu_412_p2, "tmp1_i_i_cast_fu_412_p2");
    sc_trace(mVcdFile, tmp1_i_i_cast_reg_533, "tmp1_i_i_cast_reg_533");
    sc_trace(mVcdFile, tmp_i_i_cast_fu_418_p2, "tmp_i_i_cast_fu_418_p2");
    sc_trace(mVcdFile, tmp_i_i_cast_reg_538, "tmp_i_i_cast_reg_538");
    sc_trace(mVcdFile, tmp_5_fu_360_p1, "tmp_5_fu_360_p1");
    sc_trace(mVcdFile, tmp_5_reg_543, "tmp_5_reg_543");
    sc_trace(mVcdFile, complex_M_real_V_wr_1_fu_400_p2, "complex_M_real_V_wr_1_fu_400_p2");
    sc_trace(mVcdFile, complex_M_real_V_wr_1_reg_559, "complex_M_real_V_wr_1_reg_559");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, complex_M_imag_V_wr_1_fu_406_p2, "complex_M_imag_V_wr_1_fu_406_p2");
    sc_trace(mVcdFile, complex_M_imag_V_wr_1_reg_564, "complex_M_imag_V_wr_1_reg_564");
    sc_trace(mVcdFile, butterfly_span_reg_186, "butterfly_span_reg_186");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, butterfly_pass_reg_197, "butterfly_pass_reg_197");
    sc_trace(mVcdFile, i_reg_208, "i_reg_208");
    sc_trace(mVcdFile, tmp_3_fu_287_p1, "tmp_3_fu_287_p1");
    sc_trace(mVcdFile, complex_M_real_V_wr_fu_386_p2, "complex_M_real_V_wr_fu_386_p2");
    sc_trace(mVcdFile, complex_M_imag_V_wr_fu_393_p2, "complex_M_imag_V_wr_fu_393_p2");
    sc_trace(mVcdFile, tmp_11_fu_231_p1, "tmp_11_fu_231_p1");
    sc_trace(mVcdFile, tmp_fu_235_p2, "tmp_fu_235_p2");
    sc_trace(mVcdFile, tmp_12_fu_245_p1, "tmp_12_fu_245_p1");
    sc_trace(mVcdFile, tmp_s_fu_249_p2, "tmp_s_fu_249_p2");
    sc_trace(mVcdFile, tmp_2_fu_276_p2, "tmp_2_fu_276_p2");
    sc_trace(mVcdFile, index_fu_271_p2, "index_fu_271_p2");
    sc_trace(mVcdFile, tmp_7_fu_304_p2, "tmp_7_fu_304_p2");
    sc_trace(mVcdFile, butterfly_pass_3_fu_309_p2, "butterfly_pass_3_fu_309_p2");
    sc_trace(mVcdFile, tmp_6_fu_293_p2, "tmp_6_fu_293_p2");
    sc_trace(mVcdFile, butterfly_span_1_fu_298_p2, "butterfly_span_1_fu_298_p2");
    sc_trace(mVcdFile, butterfly_pass_1_fu_315_p3, "butterfly_pass_1_fu_315_p3");
    sc_trace(mVcdFile, Llimit_fu_339_p2, "Llimit_fu_339_p2");
    sc_trace(mVcdFile, grp_fu_424_p3, "grp_fu_424_p3");
    sc_trace(mVcdFile, grp_fu_431_p3, "grp_fu_431_p3");
    sc_trace(mVcdFile, p_Val2_3_fu_368_p4, "p_Val2_3_fu_368_p4");
    sc_trace(mVcdFile, p_Val2_5_fu_377_p4, "p_Val2_5_fu_377_p4");
    sc_trace(mVcdFile, tmp1_i_i_cast_fu_412_p1, "tmp1_i_i_cast_fu_412_p1");
    sc_trace(mVcdFile, tmp_8_fu_353_p1, "tmp_8_fu_353_p1");
    sc_trace(mVcdFile, tmp_i_i_cast_fu_418_p1, "tmp_i_i_cast_fu_418_p1");
    sc_trace(mVcdFile, grp_fu_424_p0, "grp_fu_424_p0");
    sc_trace(mVcdFile, grp_fu_424_p1, "grp_fu_424_p1");
    sc_trace(mVcdFile, tmp_10_fu_365_p1, "tmp_10_fu_365_p1");
    sc_trace(mVcdFile, grp_fu_431_p0, "grp_fu_431_p0");
    sc_trace(mVcdFile, grp_fu_431_p1, "grp_fu_431_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

FFT0::~FFT0() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete W_M_real_V_U;
    delete W_M_imag_V_U;
    delete FFT_mul_mul_16s_1bkb_U1;
    delete FFT_mul_mul_16s_1bkb_U2;
    delete FFT_mac_mulsub_16cud_U3;
    delete FFT_mac_muladd_9sdEe_U4;
}

void FFT0::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        butterfly_pass_reg_197 = butterfly_pass_2_reg_492.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        butterfly_pass_reg_197 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        butterfly_span_reg_186 = butterfly_span_2_reg_487.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        butterfly_span_reg_186 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        i_reg_208 = i_1_reg_466.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_reg_208 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        FFT_stage_cast1_reg_448 = FFT_stage_cast1_fu_227_p1.read();
        index_shift_cast_reg_443 = index_shift_cast_fu_223_p1.read();
        pass_shift_cast_reg_438 = pass_shift_cast_fu_219_p1.read();
        tmp_cast_11_reg_458 = tmp_cast_11_fu_255_p1.read();
        tmp_cast_reg_453 = tmp_cast_fu_241_p1.read();
    }
    if ((esl_seteq<1,1,1>(exitcond_fu_259_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        Ulimit_reg_471 = Ulimit_fu_281_p2.read();
        butterfly_pass_2_reg_492 = butterfly_pass_2_fu_331_p3.read();
        butterfly_span_2_reg_487 = butterfly_span_2_fu_323_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        complex_M_imag_V_wr_1_reg_564 = complex_M_imag_V_wr_1_fu_406_p2.read();
        complex_M_real_V_wr_1_reg_559 = complex_M_real_V_wr_1_fu_400_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_1_reg_466 = i_1_fu_265_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        p_r_M_imag_V_reg_518 = W_M_imag_V_q0.read();
        p_r_M_real_V_reg_513 = W_M_real_V_q0.read();
        tmp_4_reg_497 = tmp_4_fu_343_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        tmp1_i_i_cast_reg_533 = tmp1_i_i_cast_fu_412_p2.read();
        tmp_1_reg_523 = tmp_1_fu_349_p1.read();
        tmp_5_reg_543 = tmp_5_fu_360_p1.read();
        tmp_9_reg_528 = tmp_9_fu_356_p1.read();
        tmp_i_i_cast_reg_538 = tmp_i_i_cast_fu_418_p2.read();
    }
}

void FFT0::thread_FFT_stage_cast1_fu_227_p1() {
    FFT_stage_cast1_fu_227_p1 = esl_zext<32,6>(FFT_stage.read());
}

void FFT0::thread_Llimit_fu_339_p2() {
    Llimit_fu_339_p2 = (!Ulimit_reg_471.read().is_01() || !FFT_stage_cast1_reg_448.read().is_01())? sc_lv<32>(): (sc_bigint<32>(Ulimit_reg_471.read()) + sc_biguint<32>(FFT_stage_cast1_reg_448.read()));
}

void FFT0::thread_Ulimit_fu_281_p2() {
    Ulimit_fu_281_p2 = (!tmp_2_fu_276_p2.read().is_01() || !butterfly_span_reg_186.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_2_fu_276_p2.read()) + sc_biguint<32>(butterfly_span_reg_186.read()));
}

void FFT0::thread_W_M_imag_V_address0() {
    W_M_imag_V_address0 =  (sc_lv<4>) (tmp_3_fu_287_p1.read());
}

void FFT0::thread_W_M_imag_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        W_M_imag_V_ce0 = ap_const_logic_1;
    } else {
        W_M_imag_V_ce0 = ap_const_logic_0;
    }
}

void FFT0::thread_W_M_real_V_address0() {
    W_M_real_V_address0 =  (sc_lv<4>) (tmp_3_fu_287_p1.read());
}

void FFT0::thread_W_M_real_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        W_M_real_V_ce0 = ap_const_logic_1;
    } else {
        W_M_real_V_ce0 = ap_const_logic_0;
    }
}

void FFT0::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void FFT0::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void FFT0::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void FFT0::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void FFT0::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void FFT0::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void FFT0::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(exitcond_fu_259_p2.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void FFT0::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void FFT0::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(exitcond_fu_259_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void FFT0::thread_butterfly_pass_1_fu_315_p3() {
    butterfly_pass_1_fu_315_p3 = (!tmp_7_fu_304_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_7_fu_304_p2.read()[0].to_bool())? butterfly_pass_3_fu_309_p2.read(): ap_const_lv32_0);
}

void FFT0::thread_butterfly_pass_2_fu_331_p3() {
    butterfly_pass_2_fu_331_p3 = (!tmp_6_fu_293_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_6_fu_293_p2.read()[0].to_bool())? butterfly_pass_reg_197.read(): butterfly_pass_1_fu_315_p3.read());
}

void FFT0::thread_butterfly_pass_3_fu_309_p2() {
    butterfly_pass_3_fu_309_p2 = (!butterfly_pass_reg_197.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(butterfly_pass_reg_197.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void FFT0::thread_butterfly_span_1_fu_298_p2() {
    butterfly_span_1_fu_298_p2 = (!butterfly_span_reg_186.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(butterfly_span_reg_186.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void FFT0::thread_butterfly_span_2_fu_323_p3() {
    butterfly_span_2_fu_323_p3 = (!tmp_6_fu_293_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_6_fu_293_p2.read()[0].to_bool())? butterfly_span_1_fu_298_p2.read(): ap_const_lv32_0);
}

void FFT0::thread_complex_M_imag_V_wr_1_fu_406_p2() {
    complex_M_imag_V_wr_1_fu_406_p2 = (!data_IN_M_imag_V_q0.read().is_01() || !p_Val2_5_fu_377_p4.read().is_01())? sc_lv<16>(): (sc_biguint<16>(data_IN_M_imag_V_q0.read()) + sc_biguint<16>(p_Val2_5_fu_377_p4.read()));
}

void FFT0::thread_complex_M_imag_V_wr_fu_393_p2() {
    complex_M_imag_V_wr_fu_393_p2 = (!data_IN_M_imag_V_q0.read().is_01() || !p_Val2_5_fu_377_p4.read().is_01())? sc_lv<16>(): (sc_biguint<16>(data_IN_M_imag_V_q0.read()) - sc_biguint<16>(p_Val2_5_fu_377_p4.read()));
}

void FFT0::thread_complex_M_real_V_wr_1_fu_400_p2() {
    complex_M_real_V_wr_1_fu_400_p2 = (!data_IN_M_real_V_q0.read().is_01() || !p_Val2_3_fu_368_p4.read().is_01())? sc_lv<16>(): (sc_biguint<16>(data_IN_M_real_V_q0.read()) + sc_biguint<16>(p_Val2_3_fu_368_p4.read()));
}

void FFT0::thread_complex_M_real_V_wr_fu_386_p2() {
    complex_M_real_V_wr_fu_386_p2 = (!data_IN_M_real_V_q0.read().is_01() || !p_Val2_3_fu_368_p4.read().is_01())? sc_lv<16>(): (sc_biguint<16>(data_IN_M_real_V_q0.read()) - sc_biguint<16>(p_Val2_3_fu_368_p4.read()));
}

void FFT0::thread_data_IN_M_imag_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        data_IN_M_imag_V_address0 =  (sc_lv<5>) (tmp_5_fu_360_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        data_IN_M_imag_V_address0 =  (sc_lv<5>) (tmp_4_fu_343_p1.read());
    } else {
        data_IN_M_imag_V_address0 = "XXXXX";
    }
}

void FFT0::thread_data_IN_M_imag_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        data_IN_M_imag_V_ce0 = ap_const_logic_1;
    } else {
        data_IN_M_imag_V_ce0 = ap_const_logic_0;
    }
}

void FFT0::thread_data_IN_M_real_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        data_IN_M_real_V_address0 =  (sc_lv<5>) (tmp_5_fu_360_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        data_IN_M_real_V_address0 =  (sc_lv<5>) (tmp_4_fu_343_p1.read());
    } else {
        data_IN_M_real_V_address0 = "XXXXX";
    }
}

void FFT0::thread_data_IN_M_real_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        data_IN_M_real_V_ce0 = ap_const_logic_1;
    } else {
        data_IN_M_real_V_ce0 = ap_const_logic_0;
    }
}

void FFT0::thread_data_OUT_M_imag_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        data_OUT_M_imag_V_address0 =  (sc_lv<5>) (tmp_5_reg_543.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        data_OUT_M_imag_V_address0 =  (sc_lv<5>) (tmp_4_reg_497.read());
    } else {
        data_OUT_M_imag_V_address0 = "XXXXX";
    }
}

void FFT0::thread_data_OUT_M_imag_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        data_OUT_M_imag_V_ce0 = ap_const_logic_1;
    } else {
        data_OUT_M_imag_V_ce0 = ap_const_logic_0;
    }
}

void FFT0::thread_data_OUT_M_imag_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        data_OUT_M_imag_V_d0 = complex_M_imag_V_wr_1_reg_564.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        data_OUT_M_imag_V_d0 = complex_M_imag_V_wr_fu_393_p2.read();
    } else {
        data_OUT_M_imag_V_d0 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void FFT0::thread_data_OUT_M_imag_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        data_OUT_M_imag_V_we0 = ap_const_logic_1;
    } else {
        data_OUT_M_imag_V_we0 = ap_const_logic_0;
    }
}

void FFT0::thread_data_OUT_M_real_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        data_OUT_M_real_V_address0 =  (sc_lv<5>) (tmp_5_reg_543.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        data_OUT_M_real_V_address0 =  (sc_lv<5>) (tmp_4_reg_497.read());
    } else {
        data_OUT_M_real_V_address0 = "XXXXX";
    }
}

void FFT0::thread_data_OUT_M_real_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        data_OUT_M_real_V_ce0 = ap_const_logic_1;
    } else {
        data_OUT_M_real_V_ce0 = ap_const_logic_0;
    }
}

void FFT0::thread_data_OUT_M_real_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        data_OUT_M_real_V_d0 = complex_M_real_V_wr_1_reg_559.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        data_OUT_M_real_V_d0 = complex_M_real_V_wr_fu_386_p2.read();
    } else {
        data_OUT_M_real_V_d0 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void FFT0::thread_data_OUT_M_real_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        data_OUT_M_real_V_we0 = ap_const_logic_1;
    } else {
        data_OUT_M_real_V_we0 = ap_const_logic_0;
    }
}

void FFT0::thread_exitcond_fu_259_p2() {
    exitcond_fu_259_p2 = (!i_reg_208.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_208.read() == ap_const_lv5_10);
}

void FFT0::thread_grp_fu_424_p0() {
    grp_fu_424_p0 =  (sc_lv<16>) (tmp_9_reg_528.read());
}

void FFT0::thread_grp_fu_424_p1() {
    grp_fu_424_p1 =  (sc_lv<9>) (tmp_10_fu_365_p1.read());
}

void FFT0::thread_grp_fu_431_p0() {
    grp_fu_431_p0 =  (sc_lv<9>) (tmp_10_fu_365_p1.read());
}

void FFT0::thread_grp_fu_431_p1() {
    grp_fu_431_p1 =  (sc_lv<16>) (tmp_1_reg_523.read());
}

void FFT0::thread_i_1_fu_265_p2() {
    i_1_fu_265_p2 = (!i_reg_208.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_reg_208.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void FFT0::thread_index_fu_271_p2() {
    index_fu_271_p2 = (!index_shift_cast_reg_443.read().is_01())? sc_lv<32>(): butterfly_span_reg_186.read() << (unsigned short)index_shift_cast_reg_443.read().to_uint();
}

void FFT0::thread_index_shift_cast_fu_223_p1() {
    index_shift_cast_fu_223_p1 = esl_zext<32,4>(index_shift.read());
}

void FFT0::thread_p_Val2_3_fu_368_p4() {
    p_Val2_3_fu_368_p4 = grp_fu_424_p3.read().range(23, 8);
}

void FFT0::thread_p_Val2_5_fu_377_p4() {
    p_Val2_5_fu_377_p4 = grp_fu_431_p3.read().range(23, 8);
}

void FFT0::thread_pass_shift_cast_fu_219_p1() {
    pass_shift_cast_fu_219_p1 = esl_zext<32,4>(pass_shift.read());
}

void FFT0::thread_tmp1_i_i_cast_fu_412_p1() {
    tmp1_i_i_cast_fu_412_p1 =  (sc_lv<10>) (tmp_8_fu_353_p1.read());
}

void FFT0::thread_tmp_10_fu_365_p1() {
    tmp_10_fu_365_p1 = esl_sext<24,9>(p_r_M_imag_V_reg_518.read());
}

void FFT0::thread_tmp_11_fu_231_p1() {
    tmp_11_fu_231_p1 = FFT_stage.read().range(5-1, 0);
}

void FFT0::thread_tmp_12_fu_245_p1() {
    tmp_12_fu_245_p1 = pass_check.read().range(5-1, 0);
}

void FFT0::thread_tmp_1_fu_349_p1() {
    tmp_1_fu_349_p1 = esl_sext<24,16>(data_IN_M_real_V_q0.read());
}

void FFT0::thread_tmp_2_fu_276_p2() {
    tmp_2_fu_276_p2 = (!pass_shift_cast_reg_438.read().is_01())? sc_lv<32>(): butterfly_pass_reg_197.read() << (unsigned short)pass_shift_cast_reg_438.read().to_uint();
}

void FFT0::thread_tmp_3_fu_287_p1() {
    tmp_3_fu_287_p1 = esl_sext<64,32>(index_fu_271_p2.read());
}

void FFT0::thread_tmp_4_fu_343_p1() {
    tmp_4_fu_343_p1 = esl_sext<64,32>(Llimit_fu_339_p2.read());
}

void FFT0::thread_tmp_5_fu_360_p1() {
    tmp_5_fu_360_p1 = esl_sext<64,32>(Ulimit_reg_471.read());
}

void FFT0::thread_tmp_6_fu_293_p2() {
    tmp_6_fu_293_p2 = (!butterfly_span_reg_186.read().is_01() || !tmp_cast_reg_453.read().is_01())? sc_lv<1>(): (sc_bigint<32>(butterfly_span_reg_186.read()) < sc_bigint<32>(tmp_cast_reg_453.read()));
}

void FFT0::thread_tmp_7_fu_304_p2() {
    tmp_7_fu_304_p2 = (!butterfly_pass_reg_197.read().is_01() || !tmp_cast_11_reg_458.read().is_01())? sc_lv<1>(): (sc_bigint<32>(butterfly_pass_reg_197.read()) < sc_bigint<32>(tmp_cast_11_reg_458.read()));
}

void FFT0::thread_tmp_8_fu_353_p1() {
    tmp_8_fu_353_p1 = esl_sext<24,10>(p_r_M_real_V_reg_513.read());
}

void FFT0::thread_tmp_9_fu_356_p1() {
    tmp_9_fu_356_p1 = esl_sext<24,16>(data_IN_M_imag_V_q0.read());
}

void FFT0::thread_tmp_cast_11_fu_255_p1() {
    tmp_cast_11_fu_255_p1 = esl_zext<32,5>(tmp_s_fu_249_p2.read());
}

void FFT0::thread_tmp_cast_fu_241_p1() {
    tmp_cast_fu_241_p1 = esl_zext<32,5>(tmp_fu_235_p2.read());
}

void FFT0::thread_tmp_fu_235_p2() {
    tmp_fu_235_p2 = (!ap_const_lv5_1F.is_01() || !tmp_11_fu_231_p1.read().is_01())? sc_lv<5>(): (sc_bigint<5>(ap_const_lv5_1F) + sc_biguint<5>(tmp_11_fu_231_p1.read()));
}

void FFT0::thread_tmp_i_i_cast_fu_418_p1() {
    tmp_i_i_cast_fu_418_p1 =  (sc_lv<10>) (tmp_8_fu_353_p1.read());
}

void FFT0::thread_tmp_s_fu_249_p2() {
    tmp_s_fu_249_p2 = (!ap_const_lv5_1F.is_01() || !tmp_12_fu_245_p1.read().is_01())? sc_lv<5>(): (sc_bigint<5>(ap_const_lv5_1F) + sc_biguint<5>(tmp_12_fu_245_p1.read()));
}

void FFT0::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(exitcond_fu_259_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<6>) ("XXXXXX");
            break;
    }
}

}

