-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity dct_constant_r_rom is 
    generic(
             DWIDTH     : integer := 32; 
             AWIDTH     : integer := 6; 
             MEM_SIZE    : integer := 64
    ); 
    port (
          addr0      : in std_logic_vector(AWIDTH-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(DWIDTH-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of dct_constant_r_rom is 

signal addr0_tmp : std_logic_vector(AWIDTH-1 downto 0); 
type mem_array is array (0 to MEM_SIZE-1) of std_logic_vector (DWIDTH-1 downto 0); 
signal mem : mem_array := (
    0 to 7=> "00111111100000000000000000000000", 
    8 => "00111111011110110001011000000100", 
    9 => "00111111010101001110011000010000", 
    10 => "00111111000011100101010011110111", 
    11 => "00111110010010000111100011100101", 
    12 => "10111110010001101101111101100111", 
    13 => "10111111000011011111111000101010", 
    14 => "10111111010101001010110000001000", 
    15 => "10111111011110110000000110010101", 
    16 => "00111111011011001000100001011100", 
    17 => "00111110110001000011011101100110", 
    18 => "10111110110000110111011010000101", 
    19 => "10111111011011000110000001011100", 
    20 => "10111111011011001011000000110101", 
    21 => "10111110110001001111100000100110", 
    22 => "00111110110000101011010110000100", 
    23 => "00111111011011000011100000110101", 
    24 => "00111111010101001110011000010000", 
    25 => "10111110010001101101111101100111", 
    26 => "10111111011110110000000110010101", 
    27 => "10111111000011101010101110101101", 
    28 => "00111111000011011010011101000101", 
    29 => "00111111011110110011111001100101", 
    30 => "00111110010010111010101101111100", 
    31 => "10111111010101000011011110001110", 
    32 => "00111111001101010001011101100110", 
    33 => "10111111001101001100110110010000", 
    34 => "10111111001101010110000100011101", 
    35 => "00111111001101001000001110011100", 
    36 => "00111111001101011010101010110111", 
    37 => "10111111001101000011100110001011", 
    38 => "10111111001101011111010000110010", 
    39 => "00111111001100111110111101011011", 
    40 => "00111111000011100101010011110111", 
    41 => "10111111011110110000000110010101", 
    42 => "00111110010001010100010111001001", 
    43 => "00111111010101010101100110110110", 
    44 => "10111111010101000011011110001110", 
    45 => "10111110010011010100010010010100", 
    46 => "00111111011110110110011000011111", 
    47 => "10111111000011001010001000001000", 
    48 => "00111110110001000011011101100110", 
    49 => "10111111011011001011000000110101", 
    50 => "00111111011011000011100000110101", 
    51 => "10111110110000011111010001100010", 
    52 => "10111110110001100111100101000100", 
    53 => "00111111011011010010011011010100", 
    54 => "10111111011010111011111011010011", 
    55 => "00111110101111111011000000111100", 
    56 => "00111110010010000111100011100101", 
    57 => "10111111000011101010101110101101", 
    58 => "00111111010101010101100110110110", 
    59 => "10111111011110110101001001010111", 
    60 => "00111111011110101100001101001101", 
    61 => "10111111010100111100001010000111", 
    62 => "00111111000011000100101011000101", 
    63 => "10111110001111010100001111001001" );


begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity dct_constant_r is
    generic (
        DataWidth : INTEGER := 32;
        AddressRange : INTEGER := 64;
        AddressWidth : INTEGER := 6);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of dct_constant_r is
    component dct_constant_r_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;



begin
    dct_constant_r_rom_U :  component dct_constant_r_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


