# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pins.xdc

# Block Designs: bd/mb/mb.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb || ORIG_REF_NAME==mb} -quiet] -quiet

# IP: bd/mb/ip/mb_microblaze_0_0/mb_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_microblaze_0_0 || ORIG_REF_NAME==mb_microblaze_0_0} -quiet] -quiet

# IP: bd/mb/ip/mb_mdm_1_0/mb_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_mdm_1_0 || ORIG_REF_NAME==mb_mdm_1_0} -quiet] -quiet

# IP: bd/mb/ip/mb_clk_wiz_1_0/mb_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_clk_wiz_1_0 || ORIG_REF_NAME==mb_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mb/ip/mb_rst_clk_wiz_1_100M_0/mb_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mb/ip/mb_axi_uartlite_0_0/mb_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_axi_uartlite_0_0 || ORIG_REF_NAME==mb_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb/ip/mb_microblaze_0_axi_periph_0/mb_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb/ip/mb_counter_0_0/mb_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_counter_0_0 || ORIG_REF_NAME==mb_counter_0_0} -quiet] -quiet

# IP: bd/mb/ip/mb_xbar_0/mb_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_xbar_0 || ORIG_REF_NAME==mb_xbar_0} -quiet] -quiet

# IP: bd/mb/ip/mb_dlmb_v10_0/mb_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_dlmb_v10_0 || ORIG_REF_NAME==mb_dlmb_v10_0} -quiet] -quiet

# IP: bd/mb/ip/mb_ilmb_v10_0/mb_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ilmb_v10_0 || ORIG_REF_NAME==mb_ilmb_v10_0} -quiet] -quiet

# IP: bd/mb/ip/mb_dlmb_bram_if_cntlr_0/mb_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb/ip/mb_ilmb_bram_if_cntlr_0/mb_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb/ip/mb_lmb_bram_0/mb_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_lmb_bram_0 || ORIG_REF_NAME==mb_lmb_bram_0} -quiet] -quiet

# IP: bd/mb/ip/mb_FFT_0_0/mb_FFT_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_FFT_0_0 || ORIG_REF_NAME==mb_FFT_0_0} -quiet] -quiet

# XDC: bd/mb/mb_ooc.xdc
