// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="FFT,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=10.779000,HLS_SYN_LAT=673,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=4,HLS_SYN_FF=1144,HLS_SYN_LUT=1880,HLS_VERSION=2018_2}" *)

module FFT (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_IN_TDATA,
        data_IN_TVALID,
        data_IN_TREADY,
        data_OUT_TDATA,
        data_OUT_TVALID,
        data_OUT_TREADY
);

parameter    ap_ST_fsm_state1 = 18'd1;
parameter    ap_ST_fsm_state2 = 18'd2;
parameter    ap_ST_fsm_state3 = 18'd4;
parameter    ap_ST_fsm_state4 = 18'd8;
parameter    ap_ST_fsm_state5 = 18'd16;
parameter    ap_ST_fsm_state6 = 18'd32;
parameter    ap_ST_fsm_state7 = 18'd64;
parameter    ap_ST_fsm_state8 = 18'd128;
parameter    ap_ST_fsm_state9 = 18'd256;
parameter    ap_ST_fsm_state10 = 18'd512;
parameter    ap_ST_fsm_state11 = 18'd1024;
parameter    ap_ST_fsm_state12 = 18'd2048;
parameter    ap_ST_fsm_state13 = 18'd4096;
parameter    ap_ST_fsm_state14 = 18'd8192;
parameter    ap_ST_fsm_state15 = 18'd16384;
parameter    ap_ST_fsm_state16 = 18'd32768;
parameter    ap_ST_fsm_state17 = 18'd65536;
parameter    ap_ST_fsm_state18 = 18'd131072;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] data_IN_TDATA;
input   data_IN_TVALID;
output   data_IN_TREADY;
output  [31:0] data_OUT_TDATA;
output   data_OUT_TVALID;
input   data_OUT_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [17:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] data_IN_0_data_out;
wire    data_IN_0_vld_in;
wire    data_IN_0_vld_out;
wire    data_IN_0_ack_in;
reg    data_IN_0_ack_out;
reg   [31:0] data_IN_0_payload_A;
reg   [31:0] data_IN_0_payload_B;
reg    data_IN_0_sel_rd;
reg    data_IN_0_sel_wr;
wire    data_IN_0_sel;
wire    data_IN_0_load_A;
wire    data_IN_0_load_B;
reg   [1:0] data_IN_0_state;
wire    data_IN_0_state_cmp_full;
reg   [31:0] data_OUT_1_data_out;
reg    data_OUT_1_vld_in;
wire    data_OUT_1_vld_out;
wire    data_OUT_1_ack_in;
wire    data_OUT_1_ack_out;
reg   [31:0] data_OUT_1_payload_A;
reg   [31:0] data_OUT_1_payload_B;
reg    data_OUT_1_sel_rd;
reg    data_OUT_1_sel_wr;
wire    data_OUT_1_sel;
wire    data_OUT_1_load_A;
wire    data_OUT_1_load_B;
reg   [1:0] data_OUT_1_state;
wire    data_OUT_1_state_cmp_full;
reg   [4:0] xin_M_real_V_address0;
reg    xin_M_real_V_ce0;
reg    xin_M_real_V_we0;
wire   [15:0] xin_M_real_V_d0;
wire   [15:0] xin_M_real_V_q0;
reg   [4:0] xin_M_imag_V_address0;
reg    xin_M_imag_V_ce0;
reg    xin_M_imag_V_we0;
wire   [15:0] xin_M_imag_V_d0;
wire   [15:0] xin_M_imag_V_q0;
wire   [4:0] rev_32_address0;
reg    rev_32_ce0;
wire   [4:0] rev_32_q0;
reg   [4:0] data_OUT0_M_real_V_address0;
reg    data_OUT0_M_real_V_ce0;
reg    data_OUT0_M_real_V_we0;
wire   [15:0] data_OUT0_M_real_V_q0;
reg   [4:0] data_OUT0_M_imag_V_address0;
reg    data_OUT0_M_imag_V_ce0;
reg    data_OUT0_M_imag_V_we0;
wire   [15:0] data_OUT0_M_imag_V_q0;
reg   [4:0] data_OUT1_M_real_V_address0;
reg    data_OUT1_M_real_V_ce0;
reg    data_OUT1_M_real_V_we0;
wire   [15:0] data_OUT1_M_real_V_q0;
reg   [4:0] data_OUT1_M_imag_V_address0;
reg    data_OUT1_M_imag_V_ce0;
reg    data_OUT1_M_imag_V_we0;
wire   [15:0] data_OUT1_M_imag_V_q0;
reg   [4:0] data_OUT2_M_real_V_address0;
reg    data_OUT2_M_real_V_ce0;
reg    data_OUT2_M_real_V_we0;
wire   [15:0] data_OUT2_M_real_V_q0;
reg   [4:0] data_OUT2_M_imag_V_address0;
reg    data_OUT2_M_imag_V_ce0;
reg    data_OUT2_M_imag_V_we0;
wire   [15:0] data_OUT2_M_imag_V_q0;
reg   [4:0] data_OUT3_M_real_V_address0;
reg    data_OUT3_M_real_V_ce0;
reg    data_OUT3_M_real_V_we0;
wire   [15:0] data_OUT3_M_real_V_q0;
reg   [4:0] data_OUT3_M_imag_V_address0;
reg    data_OUT3_M_imag_V_ce0;
reg    data_OUT3_M_imag_V_we0;
wire   [15:0] data_OUT3_M_imag_V_q0;
reg   [4:0] data_OUT4_M_real_V_address0;
reg    data_OUT4_M_real_V_ce0;
reg    data_OUT4_M_real_V_we0;
wire   [15:0] data_OUT4_M_real_V_q0;
reg   [4:0] data_OUT4_M_imag_V_address0;
reg    data_OUT4_M_imag_V_ce0;
reg    data_OUT4_M_imag_V_we0;
wire   [15:0] data_OUT4_M_imag_V_q0;
reg   [4:0] xout_M_real_V_address0;
reg    xout_M_real_V_ce0;
reg    xout_M_real_V_we0;
wire   [15:0] xout_M_real_V_q0;
reg   [4:0] xout_M_imag_V_address0;
reg    xout_M_imag_V_ce0;
reg    xout_M_imag_V_we0;
wire   [15:0] xout_M_imag_V_q0;
reg    data_IN_TDATA_blk_n;
wire    ap_CS_fsm_state3;
reg    data_OUT_TDATA_blk_n;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire   [5:0] i_2_fu_324_p2;
reg   [5:0] i_2_reg_405;
wire    ap_CS_fsm_state2;
wire   [5:0] i_3_fu_358_p2;
reg   [5:0] i_3_reg_413;
wire    ap_CS_fsm_state4;
wire   [63:0] tmp_i_fu_364_p1;
reg   [63:0] tmp_i_reg_418;
wire   [0:0] exitcond_i_fu_352_p2;
wire    ap_CS_fsm_state5;
wire   [5:0] i_4_fu_381_p2;
reg   [5:0] i_4_reg_442;
wire    ap_CS_fsm_state16;
wire   [0:0] exitcond_fu_375_p2;
wire   [31:0] data_OUT_M_imag_V_a_fu_393_p3;
wire    grp_FFT0_fu_262_ap_start;
wire    grp_FFT0_fu_262_ap_done;
wire    grp_FFT0_fu_262_ap_idle;
wire    grp_FFT0_fu_262_ap_ready;
reg   [5:0] grp_FFT0_fu_262_FFT_stage;
reg   [5:0] grp_FFT0_fu_262_pass_check;
reg   [3:0] grp_FFT0_fu_262_index_shift;
reg   [3:0] grp_FFT0_fu_262_pass_shift;
wire   [4:0] grp_FFT0_fu_262_data_IN_M_real_V_address0;
wire    grp_FFT0_fu_262_data_IN_M_real_V_ce0;
reg   [15:0] grp_FFT0_fu_262_data_IN_M_real_V_q0;
wire   [4:0] grp_FFT0_fu_262_data_IN_M_imag_V_address0;
wire    grp_FFT0_fu_262_data_IN_M_imag_V_ce0;
reg   [15:0] grp_FFT0_fu_262_data_IN_M_imag_V_q0;
wire   [4:0] grp_FFT0_fu_262_data_OUT_M_real_V_address0;
wire    grp_FFT0_fu_262_data_OUT_M_real_V_ce0;
wire    grp_FFT0_fu_262_data_OUT_M_real_V_we0;
wire   [15:0] grp_FFT0_fu_262_data_OUT_M_real_V_d0;
wire   [4:0] grp_FFT0_fu_262_data_OUT_M_imag_V_address0;
wire    grp_FFT0_fu_262_data_OUT_M_imag_V_ce0;
wire    grp_FFT0_fu_262_data_OUT_M_imag_V_we0;
wire   [15:0] grp_FFT0_fu_262_data_OUT_M_imag_V_d0;
reg   [5:0] i_reg_228;
reg   [5:0] i_i_reg_240;
wire    ap_CS_fsm_state6;
wire   [0:0] exitcond1_fu_318_p2;
reg   [5:0] i1_reg_251;
wire    ap_CS_fsm_state15;
reg    grp_FFT0_fu_262_ap_start_reg;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state13;
wire   [63:0] tmp_s_fu_330_p1;
wire   [63:0] tmp_i_13_fu_369_p1;
wire   [63:0] tmp_8_fu_387_p1;
reg   [17:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 18'd1;
#0 data_IN_0_sel_rd = 1'b0;
#0 data_IN_0_sel_wr = 1'b0;
#0 data_IN_0_state = 2'd0;
#0 data_OUT_1_sel_rd = 1'b0;
#0 data_OUT_1_sel_wr = 1'b0;
#0 data_OUT_1_state = 2'd0;
#0 grp_FFT0_fu_262_ap_start_reg = 1'b0;
end

FFT_xin_M_real_V #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
xin_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(xin_M_real_V_address0),
    .ce0(xin_M_real_V_ce0),
    .we0(xin_M_real_V_we0),
    .d0(xin_M_real_V_d0),
    .q0(xin_M_real_V_q0)
);

FFT_xin_M_real_V #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
xin_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(xin_M_imag_V_address0),
    .ce0(xin_M_imag_V_ce0),
    .we0(xin_M_imag_V_we0),
    .d0(xin_M_imag_V_d0),
    .q0(xin_M_imag_V_q0)
);

FFT_rev_32 #(
    .DataWidth( 5 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
rev_32_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(rev_32_address0),
    .ce0(rev_32_ce0),
    .q0(rev_32_q0)
);

FFT_xin_M_real_V #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
data_OUT0_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(data_OUT0_M_real_V_address0),
    .ce0(data_OUT0_M_real_V_ce0),
    .we0(data_OUT0_M_real_V_we0),
    .d0(xin_M_real_V_q0),
    .q0(data_OUT0_M_real_V_q0)
);

FFT_xin_M_real_V #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
data_OUT0_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(data_OUT0_M_imag_V_address0),
    .ce0(data_OUT0_M_imag_V_ce0),
    .we0(data_OUT0_M_imag_V_we0),
    .d0(xin_M_imag_V_q0),
    .q0(data_OUT0_M_imag_V_q0)
);

FFT_xin_M_real_V #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
data_OUT1_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(data_OUT1_M_real_V_address0),
    .ce0(data_OUT1_M_real_V_ce0),
    .we0(data_OUT1_M_real_V_we0),
    .d0(grp_FFT0_fu_262_data_OUT_M_real_V_d0),
    .q0(data_OUT1_M_real_V_q0)
);

FFT_xin_M_real_V #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
data_OUT1_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(data_OUT1_M_imag_V_address0),
    .ce0(data_OUT1_M_imag_V_ce0),
    .we0(data_OUT1_M_imag_V_we0),
    .d0(grp_FFT0_fu_262_data_OUT_M_imag_V_d0),
    .q0(data_OUT1_M_imag_V_q0)
);

FFT_xin_M_real_V #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
data_OUT2_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(data_OUT2_M_real_V_address0),
    .ce0(data_OUT2_M_real_V_ce0),
    .we0(data_OUT2_M_real_V_we0),
    .d0(grp_FFT0_fu_262_data_OUT_M_real_V_d0),
    .q0(data_OUT2_M_real_V_q0)
);

FFT_xin_M_real_V #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
data_OUT2_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(data_OUT2_M_imag_V_address0),
    .ce0(data_OUT2_M_imag_V_ce0),
    .we0(data_OUT2_M_imag_V_we0),
    .d0(grp_FFT0_fu_262_data_OUT_M_imag_V_d0),
    .q0(data_OUT2_M_imag_V_q0)
);

FFT_xin_M_real_V #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
data_OUT3_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(data_OUT3_M_real_V_address0),
    .ce0(data_OUT3_M_real_V_ce0),
    .we0(data_OUT3_M_real_V_we0),
    .d0(grp_FFT0_fu_262_data_OUT_M_real_V_d0),
    .q0(data_OUT3_M_real_V_q0)
);

FFT_xin_M_real_V #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
data_OUT3_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(data_OUT3_M_imag_V_address0),
    .ce0(data_OUT3_M_imag_V_ce0),
    .we0(data_OUT3_M_imag_V_we0),
    .d0(grp_FFT0_fu_262_data_OUT_M_imag_V_d0),
    .q0(data_OUT3_M_imag_V_q0)
);

FFT_xin_M_real_V #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
data_OUT4_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(data_OUT4_M_real_V_address0),
    .ce0(data_OUT4_M_real_V_ce0),
    .we0(data_OUT4_M_real_V_we0),
    .d0(grp_FFT0_fu_262_data_OUT_M_real_V_d0),
    .q0(data_OUT4_M_real_V_q0)
);

FFT_xin_M_real_V #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
data_OUT4_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(data_OUT4_M_imag_V_address0),
    .ce0(data_OUT4_M_imag_V_ce0),
    .we0(data_OUT4_M_imag_V_we0),
    .d0(grp_FFT0_fu_262_data_OUT_M_imag_V_d0),
    .q0(data_OUT4_M_imag_V_q0)
);

FFT_xin_M_real_V #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
xout_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(xout_M_real_V_address0),
    .ce0(xout_M_real_V_ce0),
    .we0(xout_M_real_V_we0),
    .d0(grp_FFT0_fu_262_data_OUT_M_real_V_d0),
    .q0(xout_M_real_V_q0)
);

FFT_xin_M_real_V #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
xout_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(xout_M_imag_V_address0),
    .ce0(xout_M_imag_V_ce0),
    .we0(xout_M_imag_V_we0),
    .d0(grp_FFT0_fu_262_data_OUT_M_imag_V_d0),
    .q0(xout_M_imag_V_q0)
);

FFT0 grp_FFT0_fu_262(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_FFT0_fu_262_ap_start),
    .ap_done(grp_FFT0_fu_262_ap_done),
    .ap_idle(grp_FFT0_fu_262_ap_idle),
    .ap_ready(grp_FFT0_fu_262_ap_ready),
    .FFT_stage(grp_FFT0_fu_262_FFT_stage),
    .pass_check(grp_FFT0_fu_262_pass_check),
    .index_shift(grp_FFT0_fu_262_index_shift),
    .pass_shift(grp_FFT0_fu_262_pass_shift),
    .data_IN_M_real_V_address0(grp_FFT0_fu_262_data_IN_M_real_V_address0),
    .data_IN_M_real_V_ce0(grp_FFT0_fu_262_data_IN_M_real_V_ce0),
    .data_IN_M_real_V_q0(grp_FFT0_fu_262_data_IN_M_real_V_q0),
    .data_IN_M_imag_V_address0(grp_FFT0_fu_262_data_IN_M_imag_V_address0),
    .data_IN_M_imag_V_ce0(grp_FFT0_fu_262_data_IN_M_imag_V_ce0),
    .data_IN_M_imag_V_q0(grp_FFT0_fu_262_data_IN_M_imag_V_q0),
    .data_OUT_M_real_V_address0(grp_FFT0_fu_262_data_OUT_M_real_V_address0),
    .data_OUT_M_real_V_ce0(grp_FFT0_fu_262_data_OUT_M_real_V_ce0),
    .data_OUT_M_real_V_we0(grp_FFT0_fu_262_data_OUT_M_real_V_we0),
    .data_OUT_M_real_V_d0(grp_FFT0_fu_262_data_OUT_M_real_V_d0),
    .data_OUT_M_imag_V_address0(grp_FFT0_fu_262_data_OUT_M_imag_V_address0),
    .data_OUT_M_imag_V_ce0(grp_FFT0_fu_262_data_OUT_M_imag_V_ce0),
    .data_OUT_M_imag_V_we0(grp_FFT0_fu_262_data_OUT_M_imag_V_we0),
    .data_OUT_M_imag_V_d0(grp_FFT0_fu_262_data_OUT_M_imag_V_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        data_IN_0_sel_rd <= 1'b0;
    end else begin
        if (((data_IN_0_ack_out == 1'b1) & (data_IN_0_vld_out == 1'b1))) begin
            data_IN_0_sel_rd <= ~data_IN_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        data_IN_0_sel_wr <= 1'b0;
    end else begin
        if (((data_IN_0_ack_in == 1'b1) & (data_IN_0_vld_in == 1'b1))) begin
            data_IN_0_sel_wr <= ~data_IN_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        data_IN_0_state <= 2'd0;
    end else begin
        if ((((data_IN_0_state == 2'd2) & (data_IN_0_vld_in == 1'b0)) | ((data_IN_0_state == 2'd3) & (data_IN_0_vld_in == 1'b0) & (data_IN_0_ack_out == 1'b1)))) begin
            data_IN_0_state <= 2'd2;
        end else if ((((data_IN_0_state == 2'd1) & (data_IN_0_ack_out == 1'b0)) | ((data_IN_0_state == 2'd3) & (data_IN_0_ack_out == 1'b0) & (data_IN_0_vld_in == 1'b1)))) begin
            data_IN_0_state <= 2'd1;
        end else if (((~((data_IN_0_vld_in == 1'b0) & (data_IN_0_ack_out == 1'b1)) & ~((data_IN_0_ack_out == 1'b0) & (data_IN_0_vld_in == 1'b1)) & (data_IN_0_state == 2'd3)) | ((data_IN_0_state == 2'd1) & (data_IN_0_ack_out == 1'b1)) | ((data_IN_0_state == 2'd2) & (data_IN_0_vld_in == 1'b1)))) begin
            data_IN_0_state <= 2'd3;
        end else begin
            data_IN_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        data_OUT_1_sel_rd <= 1'b0;
    end else begin
        if (((data_OUT_1_ack_out == 1'b1) & (data_OUT_1_vld_out == 1'b1))) begin
            data_OUT_1_sel_rd <= ~data_OUT_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        data_OUT_1_sel_wr <= 1'b0;
    end else begin
        if (((data_OUT_1_ack_in == 1'b1) & (data_OUT_1_vld_in == 1'b1))) begin
            data_OUT_1_sel_wr <= ~data_OUT_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        data_OUT_1_state <= 2'd0;
    end else begin
        if ((((data_OUT_1_state == 2'd2) & (data_OUT_1_vld_in == 1'b0)) | ((data_OUT_1_state == 2'd3) & (data_OUT_1_vld_in == 1'b0) & (data_OUT_1_ack_out == 1'b1)))) begin
            data_OUT_1_state <= 2'd2;
        end else if ((((data_OUT_1_state == 2'd1) & (data_OUT_1_ack_out == 1'b0)) | ((data_OUT_1_state == 2'd3) & (data_OUT_1_ack_out == 1'b0) & (data_OUT_1_vld_in == 1'b1)))) begin
            data_OUT_1_state <= 2'd1;
        end else if (((~((data_OUT_1_vld_in == 1'b0) & (data_OUT_1_ack_out == 1'b1)) & ~((data_OUT_1_ack_out == 1'b0) & (data_OUT_1_vld_in == 1'b1)) & (data_OUT_1_state == 2'd3)) | ((data_OUT_1_state == 2'd1) & (data_OUT_1_ack_out == 1'b1)) | ((data_OUT_1_state == 2'd2) & (data_OUT_1_vld_in == 1'b1)))) begin
            data_OUT_1_state <= 2'd3;
        end else begin
            data_OUT_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_FFT0_fu_262_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8) | ((exitcond_i_fu_352_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)))) begin
            grp_FFT0_fu_262_ap_start_reg <= 1'b1;
        end else if ((grp_FFT0_fu_262_ap_ready == 1'b1)) begin
            grp_FFT0_fu_262_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state18) & (data_OUT_1_ack_in == 1'b1))) begin
        i1_reg_251 <= i_4_reg_442;
    end else if (((grp_FFT0_fu_262_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        i1_reg_251 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_318_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i_i_reg_240 <= 6'd0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        i_i_reg_240 <= i_3_reg_413;
    end
end

always @ (posedge ap_clk) begin
    if (((data_IN_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        i_reg_228 <= i_2_reg_405;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_228 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((data_IN_0_load_A == 1'b1)) begin
        data_IN_0_payload_A <= data_IN_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((data_IN_0_load_B == 1'b1)) begin
        data_IN_0_payload_B <= data_IN_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((data_OUT_1_load_A == 1'b1)) begin
        data_OUT_1_payload_A <= data_OUT_M_imag_V_a_fu_393_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((data_OUT_1_load_B == 1'b1)) begin
        data_OUT_1_payload_B <= data_OUT_M_imag_V_a_fu_393_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_2_reg_405 <= i_2_fu_324_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        i_3_reg_413 <= i_3_fu_358_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state16) & (data_OUT_1_ack_in == 1'b1))) begin
        i_4_reg_442 <= i_4_fu_381_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_i_reg_418[5 : 0] <= tmp_i_fu_364_p1[5 : 0];
    end
end

always @ (*) begin
    if (((exitcond_fu_375_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16) & (data_OUT_1_ack_in == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_fu_375_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16) & (data_OUT_1_ack_in == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((data_IN_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        data_IN_0_ack_out = 1'b1;
    end else begin
        data_IN_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((data_IN_0_sel == 1'b1)) begin
        data_IN_0_data_out = data_IN_0_payload_B;
    end else begin
        data_IN_0_data_out = data_IN_0_payload_A;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        data_IN_TDATA_blk_n = data_IN_0_state[1'd0];
    end else begin
        data_IN_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        data_OUT0_M_imag_V_address0 = tmp_i_reg_418;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        data_OUT0_M_imag_V_address0 = grp_FFT0_fu_262_data_IN_M_imag_V_address0;
    end else begin
        data_OUT0_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        data_OUT0_M_imag_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        data_OUT0_M_imag_V_ce0 = grp_FFT0_fu_262_data_IN_M_imag_V_ce0;
    end else begin
        data_OUT0_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        data_OUT0_M_imag_V_we0 = 1'b1;
    end else begin
        data_OUT0_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        data_OUT0_M_real_V_address0 = tmp_i_reg_418;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        data_OUT0_M_real_V_address0 = grp_FFT0_fu_262_data_IN_M_real_V_address0;
    end else begin
        data_OUT0_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        data_OUT0_M_real_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        data_OUT0_M_real_V_ce0 = grp_FFT0_fu_262_data_IN_M_real_V_ce0;
    end else begin
        data_OUT0_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        data_OUT0_M_real_V_we0 = 1'b1;
    end else begin
        data_OUT0_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        data_OUT1_M_imag_V_address0 = grp_FFT0_fu_262_data_OUT_M_imag_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        data_OUT1_M_imag_V_address0 = grp_FFT0_fu_262_data_IN_M_imag_V_address0;
    end else begin
        data_OUT1_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        data_OUT1_M_imag_V_ce0 = grp_FFT0_fu_262_data_OUT_M_imag_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        data_OUT1_M_imag_V_ce0 = grp_FFT0_fu_262_data_IN_M_imag_V_ce0;
    end else begin
        data_OUT1_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        data_OUT1_M_imag_V_we0 = grp_FFT0_fu_262_data_OUT_M_imag_V_we0;
    end else begin
        data_OUT1_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        data_OUT1_M_real_V_address0 = grp_FFT0_fu_262_data_OUT_M_real_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        data_OUT1_M_real_V_address0 = grp_FFT0_fu_262_data_IN_M_real_V_address0;
    end else begin
        data_OUT1_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        data_OUT1_M_real_V_ce0 = grp_FFT0_fu_262_data_OUT_M_real_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        data_OUT1_M_real_V_ce0 = grp_FFT0_fu_262_data_IN_M_real_V_ce0;
    end else begin
        data_OUT1_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        data_OUT1_M_real_V_we0 = grp_FFT0_fu_262_data_OUT_M_real_V_we0;
    end else begin
        data_OUT1_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        data_OUT2_M_imag_V_address0 = grp_FFT0_fu_262_data_OUT_M_imag_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_OUT2_M_imag_V_address0 = grp_FFT0_fu_262_data_IN_M_imag_V_address0;
    end else begin
        data_OUT2_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        data_OUT2_M_imag_V_ce0 = grp_FFT0_fu_262_data_OUT_M_imag_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_OUT2_M_imag_V_ce0 = grp_FFT0_fu_262_data_IN_M_imag_V_ce0;
    end else begin
        data_OUT2_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        data_OUT2_M_imag_V_we0 = grp_FFT0_fu_262_data_OUT_M_imag_V_we0;
    end else begin
        data_OUT2_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        data_OUT2_M_real_V_address0 = grp_FFT0_fu_262_data_OUT_M_real_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_OUT2_M_real_V_address0 = grp_FFT0_fu_262_data_IN_M_real_V_address0;
    end else begin
        data_OUT2_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        data_OUT2_M_real_V_ce0 = grp_FFT0_fu_262_data_OUT_M_real_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_OUT2_M_real_V_ce0 = grp_FFT0_fu_262_data_IN_M_real_V_ce0;
    end else begin
        data_OUT2_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        data_OUT2_M_real_V_we0 = grp_FFT0_fu_262_data_OUT_M_real_V_we0;
    end else begin
        data_OUT2_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        data_OUT3_M_imag_V_address0 = grp_FFT0_fu_262_data_OUT_M_imag_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        data_OUT3_M_imag_V_address0 = grp_FFT0_fu_262_data_IN_M_imag_V_address0;
    end else begin
        data_OUT3_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        data_OUT3_M_imag_V_ce0 = grp_FFT0_fu_262_data_OUT_M_imag_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        data_OUT3_M_imag_V_ce0 = grp_FFT0_fu_262_data_IN_M_imag_V_ce0;
    end else begin
        data_OUT3_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        data_OUT3_M_imag_V_we0 = grp_FFT0_fu_262_data_OUT_M_imag_V_we0;
    end else begin
        data_OUT3_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        data_OUT3_M_real_V_address0 = grp_FFT0_fu_262_data_OUT_M_real_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        data_OUT3_M_real_V_address0 = grp_FFT0_fu_262_data_IN_M_real_V_address0;
    end else begin
        data_OUT3_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        data_OUT3_M_real_V_ce0 = grp_FFT0_fu_262_data_OUT_M_real_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        data_OUT3_M_real_V_ce0 = grp_FFT0_fu_262_data_IN_M_real_V_ce0;
    end else begin
        data_OUT3_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        data_OUT3_M_real_V_we0 = grp_FFT0_fu_262_data_OUT_M_real_V_we0;
    end else begin
        data_OUT3_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        data_OUT4_M_imag_V_address0 = grp_FFT0_fu_262_data_OUT_M_imag_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        data_OUT4_M_imag_V_address0 = grp_FFT0_fu_262_data_IN_M_imag_V_address0;
    end else begin
        data_OUT4_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        data_OUT4_M_imag_V_ce0 = grp_FFT0_fu_262_data_OUT_M_imag_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        data_OUT4_M_imag_V_ce0 = grp_FFT0_fu_262_data_IN_M_imag_V_ce0;
    end else begin
        data_OUT4_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        data_OUT4_M_imag_V_we0 = grp_FFT0_fu_262_data_OUT_M_imag_V_we0;
    end else begin
        data_OUT4_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        data_OUT4_M_real_V_address0 = grp_FFT0_fu_262_data_OUT_M_real_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        data_OUT4_M_real_V_address0 = grp_FFT0_fu_262_data_IN_M_real_V_address0;
    end else begin
        data_OUT4_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        data_OUT4_M_real_V_ce0 = grp_FFT0_fu_262_data_OUT_M_real_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        data_OUT4_M_real_V_ce0 = grp_FFT0_fu_262_data_IN_M_real_V_ce0;
    end else begin
        data_OUT4_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        data_OUT4_M_real_V_we0 = grp_FFT0_fu_262_data_OUT_M_real_V_we0;
    end else begin
        data_OUT4_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((data_OUT_1_sel == 1'b1)) begin
        data_OUT_1_data_out = data_OUT_1_payload_B;
    end else begin
        data_OUT_1_data_out = data_OUT_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) & (data_OUT_1_ack_in == 1'b1))) begin
        data_OUT_1_vld_in = 1'b1;
    end else begin
        data_OUT_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17))) begin
        data_OUT_TDATA_blk_n = data_OUT_1_state[1'd1];
    end else begin
        data_OUT_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_FFT0_fu_262_FFT_stage = 6'd16;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_FFT0_fu_262_FFT_stage = 6'd8;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_FFT0_fu_262_FFT_stage = 6'd4;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_FFT0_fu_262_FFT_stage = 6'd2;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_FFT0_fu_262_FFT_stage = 6'd1;
    end else begin
        grp_FFT0_fu_262_FFT_stage = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_FFT0_fu_262_data_IN_M_imag_V_q0 = data_OUT4_M_imag_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_FFT0_fu_262_data_IN_M_imag_V_q0 = data_OUT3_M_imag_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_FFT0_fu_262_data_IN_M_imag_V_q0 = data_OUT2_M_imag_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_FFT0_fu_262_data_IN_M_imag_V_q0 = data_OUT1_M_imag_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_FFT0_fu_262_data_IN_M_imag_V_q0 = data_OUT0_M_imag_V_q0;
    end else begin
        grp_FFT0_fu_262_data_IN_M_imag_V_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_FFT0_fu_262_data_IN_M_real_V_q0 = data_OUT4_M_real_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_FFT0_fu_262_data_IN_M_real_V_q0 = data_OUT3_M_real_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_FFT0_fu_262_data_IN_M_real_V_q0 = data_OUT2_M_real_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_FFT0_fu_262_data_IN_M_real_V_q0 = data_OUT1_M_real_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_FFT0_fu_262_data_IN_M_real_V_q0 = data_OUT0_M_real_V_q0;
    end else begin
        grp_FFT0_fu_262_data_IN_M_real_V_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_FFT0_fu_262_index_shift = 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_FFT0_fu_262_index_shift = 4'd1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_FFT0_fu_262_index_shift = 4'd2;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_FFT0_fu_262_index_shift = 4'd3;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_FFT0_fu_262_index_shift = 4'd4;
    end else begin
        grp_FFT0_fu_262_index_shift = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_FFT0_fu_262_pass_check = 6'd1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_FFT0_fu_262_pass_check = 6'd2;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_FFT0_fu_262_pass_check = 6'd4;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_FFT0_fu_262_pass_check = 6'd8;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_FFT0_fu_262_pass_check = 6'd16;
    end else begin
        grp_FFT0_fu_262_pass_check = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_FFT0_fu_262_pass_shift = 4'd5;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_FFT0_fu_262_pass_shift = 4'd4;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_FFT0_fu_262_pass_shift = 4'd3;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_FFT0_fu_262_pass_shift = 4'd2;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_FFT0_fu_262_pass_shift = 4'd1;
    end else begin
        grp_FFT0_fu_262_pass_shift = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rev_32_ce0 = 1'b1;
    end else begin
        rev_32_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        xin_M_imag_V_address0 = tmp_i_13_fu_369_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        xin_M_imag_V_address0 = tmp_s_fu_330_p1;
    end else begin
        xin_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((data_IN_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        xin_M_imag_V_ce0 = 1'b1;
    end else begin
        xin_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((data_IN_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        xin_M_imag_V_we0 = 1'b1;
    end else begin
        xin_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        xin_M_real_V_address0 = tmp_i_13_fu_369_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        xin_M_real_V_address0 = tmp_s_fu_330_p1;
    end else begin
        xin_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((data_IN_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        xin_M_real_V_ce0 = 1'b1;
    end else begin
        xin_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((data_IN_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        xin_M_real_V_we0 = 1'b1;
    end else begin
        xin_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        xout_M_imag_V_address0 = tmp_8_fu_387_p1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        xout_M_imag_V_address0 = grp_FFT0_fu_262_data_OUT_M_imag_V_address0;
    end else begin
        xout_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) & (data_OUT_1_ack_in == 1'b1))) begin
        xout_M_imag_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        xout_M_imag_V_ce0 = grp_FFT0_fu_262_data_OUT_M_imag_V_ce0;
    end else begin
        xout_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        xout_M_imag_V_we0 = grp_FFT0_fu_262_data_OUT_M_imag_V_we0;
    end else begin
        xout_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        xout_M_real_V_address0 = tmp_8_fu_387_p1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        xout_M_real_V_address0 = grp_FFT0_fu_262_data_OUT_M_real_V_address0;
    end else begin
        xout_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) & (data_OUT_1_ack_in == 1'b1))) begin
        xout_M_real_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        xout_M_real_V_ce0 = grp_FFT0_fu_262_data_OUT_M_real_V_ce0;
    end else begin
        xout_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        xout_M_real_V_we0 = grp_FFT0_fu_262_data_OUT_M_real_V_we0;
    end else begin
        xout_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond1_fu_318_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((data_IN_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((exitcond_i_fu_352_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_FFT0_fu_262_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_FFT0_fu_262_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_FFT0_fu_262_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((grp_FFT0_fu_262_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((grp_FFT0_fu_262_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((exitcond_fu_375_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16) & (data_OUT_1_ack_in == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((exitcond_fu_375_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state16) & (data_OUT_1_ack_in == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            if (((1'b1 == ap_CS_fsm_state17) & (data_OUT_1_ack_in == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((1'b1 == ap_CS_fsm_state18) & (data_OUT_1_ack_in == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign data_IN_0_ack_in = data_IN_0_state[1'd1];

assign data_IN_0_load_A = (~data_IN_0_sel_wr & data_IN_0_state_cmp_full);

assign data_IN_0_load_B = (data_IN_0_state_cmp_full & data_IN_0_sel_wr);

assign data_IN_0_sel = data_IN_0_sel_rd;

assign data_IN_0_state_cmp_full = ((data_IN_0_state != 2'd1) ? 1'b1 : 1'b0);

assign data_IN_0_vld_in = data_IN_TVALID;

assign data_IN_0_vld_out = data_IN_0_state[1'd0];

assign data_IN_TREADY = data_IN_0_state[1'd1];

assign data_OUT_1_ack_in = data_OUT_1_state[1'd1];

assign data_OUT_1_ack_out = data_OUT_TREADY;

assign data_OUT_1_load_A = (~data_OUT_1_sel_wr & data_OUT_1_state_cmp_full);

assign data_OUT_1_load_B = (data_OUT_1_state_cmp_full & data_OUT_1_sel_wr);

assign data_OUT_1_sel = data_OUT_1_sel_rd;

assign data_OUT_1_state_cmp_full = ((data_OUT_1_state != 2'd1) ? 1'b1 : 1'b0);

assign data_OUT_1_vld_out = data_OUT_1_state[1'd0];

assign data_OUT_M_imag_V_a_fu_393_p3 = {{xout_M_imag_V_q0}, {xout_M_real_V_q0}};

assign data_OUT_TDATA = data_OUT_1_data_out;

assign data_OUT_TVALID = data_OUT_1_state[1'd0];

assign exitcond1_fu_318_p2 = ((i_reg_228 == 6'd32) ? 1'b1 : 1'b0);

assign exitcond_fu_375_p2 = ((i1_reg_251 == 6'd32) ? 1'b1 : 1'b0);

assign exitcond_i_fu_352_p2 = ((i_i_reg_240 == 6'd32) ? 1'b1 : 1'b0);

assign grp_FFT0_fu_262_ap_start = grp_FFT0_fu_262_ap_start_reg;

assign i_2_fu_324_p2 = (i_reg_228 + 6'd1);

assign i_3_fu_358_p2 = (i_i_reg_240 + 6'd1);

assign i_4_fu_381_p2 = (i1_reg_251 + 6'd1);

assign rev_32_address0 = tmp_i_fu_364_p1;

assign tmp_8_fu_387_p1 = i1_reg_251;

assign tmp_i_13_fu_369_p1 = rev_32_q0;

assign tmp_i_fu_364_p1 = i_i_reg_240;

assign tmp_s_fu_330_p1 = i_reg_228;

assign xin_M_imag_V_d0 = {{data_IN_0_data_out[31:16]}};

assign xin_M_real_V_d0 = data_IN_0_data_out[15:0];

always @ (posedge ap_clk) begin
    tmp_i_reg_418[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //FFT
