// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __dct_constant_r_H__
#define __dct_constant_r_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct dct_constant_r_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 32;
  static const unsigned AddressRange = 64;
  static const unsigned AddressWidth = 6;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(dct_constant_r_ram) {
        for (unsigned i = 0; i < 8 ; i = i + 1) {
            ram[i] = "0b00111111100000000000000000000000";
        }
        ram[8] = "0b00111111011110110001011000000100";
        ram[9] = "0b00111111010101001110011000010000";
        ram[10] = "0b00111111000011100101010011110111";
        ram[11] = "0b00111110010010000111100011100101";
        ram[12] = "0b10111110010001101101111101100111";
        ram[13] = "0b10111111000011011111111000101010";
        ram[14] = "0b10111111010101001010110000001000";
        ram[15] = "0b10111111011110110000000110010101";
        ram[16] = "0b00111111011011001000100001011100";
        ram[17] = "0b00111110110001000011011101100110";
        ram[18] = "0b10111110110000110111011010000101";
        ram[19] = "0b10111111011011000110000001011100";
        ram[20] = "0b10111111011011001011000000110101";
        ram[21] = "0b10111110110001001111100000100110";
        ram[22] = "0b00111110110000101011010110000100";
        ram[23] = "0b00111111011011000011100000110101";
        ram[24] = "0b00111111010101001110011000010000";
        ram[25] = "0b10111110010001101101111101100111";
        ram[26] = "0b10111111011110110000000110010101";
        ram[27] = "0b10111111000011101010101110101101";
        ram[28] = "0b00111111000011011010011101000101";
        ram[29] = "0b00111111011110110011111001100101";
        ram[30] = "0b00111110010010111010101101111100";
        ram[31] = "0b10111111010101000011011110001110";
        ram[32] = "0b00111111001101010001011101100110";
        ram[33] = "0b10111111001101001100110110010000";
        ram[34] = "0b10111111001101010110000100011101";
        ram[35] = "0b00111111001101001000001110011100";
        ram[36] = "0b00111111001101011010101010110111";
        ram[37] = "0b10111111001101000011100110001011";
        ram[38] = "0b10111111001101011111010000110010";
        ram[39] = "0b00111111001100111110111101011011";
        ram[40] = "0b00111111000011100101010011110111";
        ram[41] = "0b10111111011110110000000110010101";
        ram[42] = "0b00111110010001010100010111001001";
        ram[43] = "0b00111111010101010101100110110110";
        ram[44] = "0b10111111010101000011011110001110";
        ram[45] = "0b10111110010011010100010010010100";
        ram[46] = "0b00111111011110110110011000011111";
        ram[47] = "0b10111111000011001010001000001000";
        ram[48] = "0b00111110110001000011011101100110";
        ram[49] = "0b10111111011011001011000000110101";
        ram[50] = "0b00111111011011000011100000110101";
        ram[51] = "0b10111110110000011111010001100010";
        ram[52] = "0b10111110110001100111100101000100";
        ram[53] = "0b00111111011011010010011011010100";
        ram[54] = "0b10111111011010111011111011010011";
        ram[55] = "0b00111110101111111011000000111100";
        ram[56] = "0b00111110010010000111100011100101";
        ram[57] = "0b10111111000011101010101110101101";
        ram[58] = "0b00111111010101010101100110110110";
        ram[59] = "0b10111111011110110101001001010111";
        ram[60] = "0b00111111011110101100001101001101";
        ram[61] = "0b10111111010100111100001010000111";
        ram[62] = "0b00111111000011000100101011000101";
        ram[63] = "0b10111110001111010100001111001001";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(dct_constant_r) {


static const unsigned DataWidth = 32;
static const unsigned AddressRange = 64;
static const unsigned AddressWidth = 6;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


dct_constant_r_ram* meminst;


SC_CTOR(dct_constant_r) {
meminst = new dct_constant_r_ram("dct_constant_r_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~dct_constant_r() {
    delete meminst;
}


};//endmodule
#endif
