# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/1_EE5332/assignment_2/perf_ctr/perf_ctr.srcs/sources_1/bd/mb/ip/mb_xbar_0/mb_xbar_0.xci
# IP: The module: 'mb_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/1_EE5332/assignment_2/perf_ctr/perf_ctr.srcs/sources_1/bd/mb/ip/mb_xbar_0/mb_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/1_EE5332/assignment_2/perf_ctr/perf_ctr.srcs/sources_1/bd/mb/ip/mb_xbar_0/mb_xbar_0.xci
# IP: The module: 'mb_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/1_EE5332/assignment_2/perf_ctr/perf_ctr.srcs/sources_1/bd/mb/ip/mb_xbar_0/mb_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
