// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x000 : Control signals
//         bit 0  - ap_start (Read/Write/COH)
//         bit 1  - ap_done (Read/COR)
//         bit 2  - ap_idle (Read)
//         bit 3  - ap_ready (Read)
//         bit 7  - auto_restart (Read/Write)
//         others - reserved
// 0x004 : Global Interrupt Enable Register
//         bit 0  - Global Interrupt Enable (Read/Write)
//         others - reserved
// 0x008 : IP Interrupt Enable Register (Read/Write)
//         bit 0  - Channel 0 (ap_done)
//         bit 1  - Channel 1 (ap_ready)
//         others - reserved
// 0x00c : IP Interrupt Status Register (Read/TOW)
//         bit 0  - Channel 0 (ap_done)
//         bit 1  - Channel 1 (ap_ready)
//         others - reserved
// 0x100 ~
// 0x1ff : Memory 'dataIn' (64 * 32b)
//         Word n : bit [31:0] - dataIn[n]
// 0x200 ~
// 0x2ff : Memory 'dataOut' (64 * 32b)
//         Word n : bit [31:0] - dataOut[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDCT_AXILITES_ADDR_AP_CTRL      0x000
#define XDCT_AXILITES_ADDR_GIE          0x004
#define XDCT_AXILITES_ADDR_IER          0x008
#define XDCT_AXILITES_ADDR_ISR          0x00c
#define XDCT_AXILITES_ADDR_DATAIN_BASE  0x100
#define XDCT_AXILITES_ADDR_DATAIN_HIGH  0x1ff
#define XDCT_AXILITES_WIDTH_DATAIN      32
#define XDCT_AXILITES_DEPTH_DATAIN      64
#define XDCT_AXILITES_ADDR_DATAOUT_BASE 0x200
#define XDCT_AXILITES_ADDR_DATAOUT_HIGH 0x2ff
#define XDCT_AXILITES_WIDTH_DATAOUT     32
#define XDCT_AXILITES_DEPTH_DATAOUT     64

