#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : mb.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Thu Mar 05 13:07:47 +0530 2020
# SW Build 2258646 on Thu Jun 14 20:03:12 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: mb.sh [-help]
# usage: mb.sh [-lib_map_path]
# usage: mb.sh [-noclean_files]
# usage: mb.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'mb.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm microblaze_v10_0_7 axi_lite_ipif_v3_0_4 mdm_v3_2_14 lib_cdc_v1_0_2 proc_sys_reset_v5_0_12 lib_pkg_v1_0_2 lib_srl_fifo_v1_0_2 axi_uartlite_v2_0_21 lmb_v10_v3_0_9 lmb_bram_if_cntlr_v4_0_15 blk_mem_gen_v8_4_1 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_17 fifo_generator_v13_2_2 axi_data_fifo_v2_1_16 axi_crossbar_v2_1_18 xbip_utils_v3_0_9 axi_utils_v2_0_5 xbip_pipe_v3_0_5 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_5 xbip_dsp48_multadd_v3_0_5 xbip_bram18k_v3_0_5 mult_gen_v12_0_14 floating_point_v7_1_6)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "mb.sh - Script generated by export_simulation (Vivado v2018.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/b65a" +incdir+"$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/ec67/hdl" \
    "F:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "F:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "F:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work microblaze_v10_0_7 $vhdlan_opts \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/b649/hdl/microblaze_v10_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mb/ip/mb_microblaze_0_0/sim/mb_microblaze_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mdm_v3_2_14 $vhdlan_opts \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/5125/hdl/mdm_v3_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mb/ip/mb_mdm_1_0/sim/mb_mdm_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/b65a" +incdir+"$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/ec67/hdl" \
    "$ref_dir/../../../bd/mb/ip/mb_clk_wiz_1_0/mb_clk_wiz_1_0_clk_wiz.v" \
    "$ref_dir/../../../bd/mb/ip/mb_clk_wiz_1_0/mb_clk_wiz_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mb/ip/mb_rst_clk_wiz_1_100M_0/sim/mb_rst_clk_wiz_1_100M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_uartlite_v2_0_21 $vhdlan_opts \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/a15e/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mb/ip/mb_axi_uartlite_0_0/sim/mb_axi_uartlite_0_0.vhd" \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/435a/hdl/vhdl/counter_AXILiteS_s_axi.vhd" \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/435a/hdl/vhdl/counter.vhd" \
    "$ref_dir/../../../bd/mb/ip/mb_counter_0_0/sim/mb_counter_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_v10_v3_0_9 $vhdlan_opts \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/78eb/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mb/ip/mb_dlmb_v10_0/sim/mb_dlmb_v10_0.vhd" \
    "$ref_dir/../../../bd/mb/ip/mb_ilmb_v10_0/sim/mb_ilmb_v10_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_bram_if_cntlr_v4_0_15 $vhdlan_opts \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/92fd/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mb/ip/mb_dlmb_bram_if_cntlr_0/sim/mb_dlmb_bram_if_cntlr_0.vhd" \
    "$ref_dir/../../../bd/mb/ip/mb_ilmb_bram_if_cntlr_0/sim/mb_ilmb_bram_if_cntlr_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/b65a" +incdir+"$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/ec67/hdl" \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/67d8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/b65a" +incdir+"$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/ec67/hdl" \
    "$ref_dir/../../../bd/mb/ip/mb_lmb_bram_0/sim/mb_lmb_bram_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/b65a" +incdir+"$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/ec67/hdl" \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/b65a" +incdir+"$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/ec67/hdl" \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/b65a" +incdir+"$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/ec67/hdl" \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/6020/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/b65a" +incdir+"$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/ec67/hdl" \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/7aff/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_2 $vhdlan_opts \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/b65a" +incdir+"$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/ec67/hdl" \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/b65a" +incdir+"$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/ec67/hdl" \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/247d/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/b65a" +incdir+"$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/ec67/hdl" \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/15a3/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/b65a" +incdir+"$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/ec67/hdl" \
    "$ref_dir/../../../bd/mb/ip/mb_xbar_0/sim/mb_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_9 $vhdlan_opts \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/a5f8/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_5 $vhdlan_opts \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/ec8e/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/442e/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/da55/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/ad9e/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/cd0f/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/c08f/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/6bb5/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work floating_point_v7_1_6 $vhdlan_opts \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/c4f7/hdl/floating_point_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/667d/hdl/vhdl/dct_AXILiteS_s_axi.vhd" \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/667d/hdl/vhdl/dct_constant_r.vhd" \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/667d/hdl/vhdl/dct_dmul_64ns_64nfYi.vhd" \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/667d/hdl/vhdl/dct_fadd_32ns_32nbkb.vhd" \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/667d/hdl/vhdl/dct_fmul_32ns_32ncud.vhd" \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/667d/hdl/vhdl/dct_fpext_32ns_64eOg.vhd" \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/667d/hdl/vhdl/dct_fptrunc_64ns_dEe.vhd" \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/667d/hdl/vhdl/dct.vhd" \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/667d/hdl/ip/dct_ap_dmul_4_max_dsp_64.vhd" \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/667d/hdl/ip/dct_ap_fadd_3_full_dsp_32.vhd" \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/667d/hdl/ip/dct_ap_fmul_2_max_dsp_32.vhd" \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/667d/hdl/ip/dct_ap_fpext_0_no_dsp_32.vhd" \
    "$ref_dir/../../../../perf_ctr.srcs/sources_1/bd/mb/ipshared/667d/hdl/ip/dct_ap_fptrunc_0_no_dsp_64.vhd" \
    "$ref_dir/../../../bd/mb/ip/mb_dct_0_1/sim/mb_dct_0_1.vhd" \
    "$ref_dir/../../../bd/mb/sim/mb.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.mb xil_defaultlib.glbl -o mb_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./mb_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./mb.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key mb_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc mb_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./mb.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: mb.sh [-help]\n\
Usage: mb.sh [-lib_map_path]\n\
Usage: mb.sh [-reset_run]\n\
Usage: mb.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
