// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dct_HH_
#define _dct_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "dct_fadd_32ns_32nbkb.h"
#include "dct_fmul_32ns_32ncud.h"
#include "dct_fptrunc_64ns_dEe.h"
#include "dct_fpext_32ns_64eOg.h"
#include "dct_dmul_64ns_64nfYi.h"
#include "dct_constant_r.h"
#include "dct_AXILiteS_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_AXILITES_ADDR_WIDTH = 10,
         unsigned int C_S_AXI_AXILITES_DATA_WIDTH = 32>
struct dct : public sc_module {
    // Port declarations 20
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > s_axi_AXILiteS_AWVALID;
    sc_out< sc_logic > s_axi_AXILiteS_AWREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_AWADDR;
    sc_in< sc_logic > s_axi_AXILiteS_WVALID;
    sc_out< sc_logic > s_axi_AXILiteS_WREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_WDATA;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH/8> > s_axi_AXILiteS_WSTRB;
    sc_in< sc_logic > s_axi_AXILiteS_ARVALID;
    sc_out< sc_logic > s_axi_AXILiteS_ARREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_ARADDR;
    sc_out< sc_logic > s_axi_AXILiteS_RVALID;
    sc_in< sc_logic > s_axi_AXILiteS_RREADY;
    sc_out< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_RDATA;
    sc_out< sc_lv<2> > s_axi_AXILiteS_RRESP;
    sc_out< sc_logic > s_axi_AXILiteS_BVALID;
    sc_in< sc_logic > s_axi_AXILiteS_BREADY;
    sc_out< sc_lv<2> > s_axi_AXILiteS_BRESP;
    sc_out< sc_logic > interrupt;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    dct(sc_module_name name);
    SC_HAS_PROCESS(dct);

    ~dct();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    dct_constant_r* constant_r_U;
    dct_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>* dct_AXILiteS_s_axi_U;
    dct_fadd_32ns_32nbkb<1,5,32,32,32>* dct_fadd_32ns_32nbkb_U1;
    dct_fmul_32ns_32ncud<1,4,32,32,32>* dct_fmul_32ns_32ncud_U2;
    dct_fptrunc_64ns_dEe<1,1,64,32>* dct_fptrunc_64ns_dEe_U3;
    dct_fpext_32ns_64eOg<1,1,32,64>* dct_fpext_32ns_64eOg_U4;
    dct_dmul_64ns_64nfYi<1,6,64,64,64>* dct_dmul_64ns_64nfYi_U5;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_lv<32> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_lv<6> > dataIn_address0;
    sc_signal< sc_logic > dataIn_ce0;
    sc_signal< sc_lv<32> > dataIn_q0;
    sc_signal< sc_lv<6> > dataOut_address0;
    sc_signal< sc_logic > dataOut_ce0;
    sc_signal< sc_logic > dataOut_we0;
    sc_signal< sc_lv<6> > constant_r_address0;
    sc_signal< sc_logic > constant_r_ce0;
    sc_signal< sc_lv<32> > constant_r_q0;
    sc_signal< sc_lv<32> > grp_fu_178_p2;
    sc_signal< sc_lv<32> > reg_195;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_logic > ap_CS_fsm_state14;
    sc_signal< sc_lv<64> > grp_fu_191_p2;
    sc_signal< sc_lv<64> > reg_201;
    sc_signal< sc_logic > ap_CS_fsm_state25;
    sc_signal< sc_logic > ap_CS_fsm_state31;
    sc_signal< sc_lv<4> > i_1_fu_213_p2;
    sc_signal< sc_lv<4> > i_1_reg_369;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<6> > tmp_1_fu_229_p3;
    sc_signal< sc_lv<6> > tmp_1_reg_374;
    sc_signal< sc_lv<1> > exitcond3_fu_207_p2;
    sc_signal< sc_lv<64> > tmp_5_fu_237_p3;
    sc_signal< sc_lv<64> > tmp_5_reg_380;
    sc_signal< sc_lv<6> > j_cast3_fu_245_p1;
    sc_signal< sc_lv<6> > j_cast3_reg_385;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<4> > j_1_fu_255_p2;
    sc_signal< sc_lv<4> > j_1_reg_393;
    sc_signal< sc_lv<1> > tmp_6_fu_261_p2;
    sc_signal< sc_lv<1> > tmp_6_reg_398;
    sc_signal< sc_lv<1> > exitcond2_fu_249_p2;
    sc_signal< sc_lv<6> > tmp_s_fu_271_p3;
    sc_signal< sc_lv<6> > tmp_s_reg_403;
    sc_signal< sc_lv<4> > x_1_fu_289_p2;
    sc_signal< sc_lv<4> > x_1_reg_411;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<3> > tmp_22_fu_295_p1;
    sc_signal< sc_lv<3> > tmp_22_reg_416;
    sc_signal< sc_lv<1> > exitcond1_fu_283_p2;
    sc_signal< sc_lv<64> > tmp_9_fu_309_p3;
    sc_signal< sc_lv<64> > tmp_9_reg_426;
    sc_signal< sc_lv<6> > tmp_2_fu_316_p2;
    sc_signal< sc_lv<6> > tmp_2_reg_431;
    sc_signal< sc_lv<6> > tmp_11_fu_320_p3;
    sc_signal< sc_lv<6> > tmp_11_reg_436;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<32> > constant_load_reg_441;
    sc_signal< sc_lv<4> > y_1_fu_337_p2;
    sc_signal< sc_lv<4> > y_1_reg_449;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<1> > exitcond_fu_331_p2;
    sc_signal< sc_lv<6> > tmp_17_fu_353_p2;
    sc_signal< sc_lv<6> > tmp_17_reg_459;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<32> > constant_load_1_reg_474;
    sc_signal< sc_lv<32> > grp_fu_173_p2;
    sc_signal< sc_logic > ap_CS_fsm_state19;
    sc_signal< sc_lv<64> > tmp_4_fu_187_p1;
    sc_signal< sc_lv<64> > tmp_4_reg_484;
    sc_signal< sc_lv<4> > i_reg_105;
    sc_signal< sc_lv<4> > j_reg_116;
    sc_signal< sc_logic > ap_CS_fsm_state32;
    sc_signal< sc_lv<32> > ds_reg_127;
    sc_signal< sc_lv<4> > x_reg_139;
    sc_signal< sc_lv<32> > ds_1_reg_150;
    sc_signal< sc_lv<4> > y_reg_162;
    sc_signal< sc_lv<64> > tmp_13_fu_304_p1;
    sc_signal< sc_lv<64> > tmp_15_fu_348_p1;
    sc_signal< sc_lv<64> > tmp_18_fu_358_p1;
    sc_signal< sc_lv<64> > tmp_10_fu_362_p1;
    sc_signal< sc_lv<32> > tmp_8_fu_183_p1;
    sc_signal< sc_logic > ap_CS_fsm_state15;
    sc_signal< sc_lv<32> > grp_fu_178_p0;
    sc_signal< sc_lv<32> > grp_fu_178_p1;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<64> > grp_fu_191_p0;
    sc_signal< sc_lv<64> > grp_fu_191_p1;
    sc_signal< sc_logic > ap_CS_fsm_state20;
    sc_signal< sc_logic > ap_CS_fsm_state26;
    sc_signal< sc_lv<3> > tmp_20_fu_225_p1;
    sc_signal< sc_lv<1> > tmp_fu_219_p2;
    sc_signal< sc_lv<3> > tmp_21_fu_267_p1;
    sc_signal< sc_lv<6> > x_cast2_fu_279_p1;
    sc_signal< sc_lv<6> > tmp_12_fu_299_p2;
    sc_signal< sc_lv<6> > y_cast1_fu_327_p1;
    sc_signal< sc_lv<6> > tmp_14_fu_343_p2;
    sc_signal< sc_lv<32> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<32> ap_ST_fsm_state1;
    static const sc_lv<32> ap_ST_fsm_state2;
    static const sc_lv<32> ap_ST_fsm_state3;
    static const sc_lv<32> ap_ST_fsm_state4;
    static const sc_lv<32> ap_ST_fsm_state5;
    static const sc_lv<32> ap_ST_fsm_state6;
    static const sc_lv<32> ap_ST_fsm_state7;
    static const sc_lv<32> ap_ST_fsm_state8;
    static const sc_lv<32> ap_ST_fsm_state9;
    static const sc_lv<32> ap_ST_fsm_state10;
    static const sc_lv<32> ap_ST_fsm_state11;
    static const sc_lv<32> ap_ST_fsm_state12;
    static const sc_lv<32> ap_ST_fsm_state13;
    static const sc_lv<32> ap_ST_fsm_state14;
    static const sc_lv<32> ap_ST_fsm_state15;
    static const sc_lv<32> ap_ST_fsm_state16;
    static const sc_lv<32> ap_ST_fsm_state17;
    static const sc_lv<32> ap_ST_fsm_state18;
    static const sc_lv<32> ap_ST_fsm_state19;
    static const sc_lv<32> ap_ST_fsm_state20;
    static const sc_lv<32> ap_ST_fsm_state21;
    static const sc_lv<32> ap_ST_fsm_state22;
    static const sc_lv<32> ap_ST_fsm_state23;
    static const sc_lv<32> ap_ST_fsm_state24;
    static const sc_lv<32> ap_ST_fsm_state25;
    static const sc_lv<32> ap_ST_fsm_state26;
    static const sc_lv<32> ap_ST_fsm_state27;
    static const sc_lv<32> ap_ST_fsm_state28;
    static const sc_lv<32> ap_ST_fsm_state29;
    static const sc_lv<32> ap_ST_fsm_state30;
    static const sc_lv<32> ap_ST_fsm_state31;
    static const sc_lv<32> ap_ST_fsm_state32;
    static const sc_lv<32> ap_const_lv32_0;
    static const int C_S_AXI_DATA_WIDTH;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<32> ap_const_lv32_19;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<64> ap_const_lv64_3FC6A09E60000000;
    static const sc_lv<64> ap_const_lv64_3FD0000000000000;
    static const sc_lv<64> ap_const_lv64_3FE6A09E60000000;
    static const sc_lv<64> ap_const_lv64_3FF0000000000000;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state14();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state19();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state20();
    void thread_ap_CS_fsm_state25();
    void thread_ap_CS_fsm_state26();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state31();
    void thread_ap_CS_fsm_state32();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_constant_r_address0();
    void thread_constant_r_ce0();
    void thread_dataIn_address0();
    void thread_dataIn_ce0();
    void thread_dataOut_address0();
    void thread_dataOut_ce0();
    void thread_dataOut_we0();
    void thread_exitcond1_fu_283_p2();
    void thread_exitcond2_fu_249_p2();
    void thread_exitcond3_fu_207_p2();
    void thread_exitcond_fu_331_p2();
    void thread_grp_fu_178_p0();
    void thread_grp_fu_178_p1();
    void thread_grp_fu_191_p0();
    void thread_grp_fu_191_p1();
    void thread_i_1_fu_213_p2();
    void thread_j_1_fu_255_p2();
    void thread_j_cast3_fu_245_p1();
    void thread_tmp_10_fu_362_p1();
    void thread_tmp_11_fu_320_p3();
    void thread_tmp_12_fu_299_p2();
    void thread_tmp_13_fu_304_p1();
    void thread_tmp_14_fu_343_p2();
    void thread_tmp_15_fu_348_p1();
    void thread_tmp_17_fu_353_p2();
    void thread_tmp_18_fu_358_p1();
    void thread_tmp_1_fu_229_p3();
    void thread_tmp_20_fu_225_p1();
    void thread_tmp_21_fu_267_p1();
    void thread_tmp_22_fu_295_p1();
    void thread_tmp_2_fu_316_p2();
    void thread_tmp_5_fu_237_p3();
    void thread_tmp_6_fu_261_p2();
    void thread_tmp_9_fu_309_p3();
    void thread_tmp_fu_219_p2();
    void thread_tmp_s_fu_271_p3();
    void thread_x_1_fu_289_p2();
    void thread_x_cast2_fu_279_p1();
    void thread_y_1_fu_337_p2();
    void thread_y_cast1_fu_327_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
