# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/1_EE5332/assignment_2/perf_ctr/perf_ctr.srcs/sources_1/bd/mb/ip/mb_dlmb_bram_if_cntlr_0/mb_dlmb_bram_if_cntlr_0.xci
# IP: The module: 'mb_dlmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/1_EE5332/assignment_2/perf_ctr/perf_ctr.srcs/sources_1/bd/mb/ip/mb_dlmb_bram_if_cntlr_0/mb_dlmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_dlmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/1_EE5332/assignment_2/perf_ctr/perf_ctr.srcs/sources_1/bd/mb/ip/mb_dlmb_bram_if_cntlr_0/mb_dlmb_bram_if_cntlr_0.xci
# IP: The module: 'mb_dlmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/1_EE5332/assignment_2/perf_ctr/perf_ctr.srcs/sources_1/bd/mb/ip/mb_dlmb_bram_if_cntlr_0/mb_dlmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_dlmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
